//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Namespace Starward.AnimatedVisuals -Public -WinUIVersion 3.0 -InputFile delete.json
//       
//       Input file:
//           delete.json (7840 bytes created 22:06+09:00 Aug 13 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    50 |
// |--------------------------+-------|
// | Expression animators     |     3 |
// | KeyFrame animators       |     5 |
// | Reference parameters     |     3 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     1 |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     1 |
// | CompositionSpriteShapes  |     5 |
// |--------------------------+-------|
// | Brushes                  |     2 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace Starward.AnimatedVisuals
{
    // Name:        delete
    // Frame rate:  29.9700012207031 fps
    // Frame count: 45.0000018328876
    // Duration:    1501.5 mS
    public sealed class Delete
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 1.502 seconds.
        internal const long c_durationTicks = 15015015;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new Delete_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 45.0000018328876;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 29.9700012207031;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(15015015);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 45.0000018328876;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class Delete_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 15015015;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionColorBrush _colorBrush_AlmostLightPink_FFFF99A4;
            CompositionColorBrush _colorBrush_Black;
            CompositionContainerShape _containerShape;
            CompositionPath _path;
            CompositionPathGeometry _pathGeometry_0;
            CompositionSpriteShape _spriteShape_1;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            PathKeyFrameAnimation CreatePathKeyFrameAnimation(float initialProgress, CompositionPath initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreatePathKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(5.44399977F, 2.98200011F));
                    builder.AddCubicBezier(new Vector2(5.44399977F, 2.98200011F), new Vector2(5.44399977F, 0.774999976F), new Vector2(5.44399977F, 0.774999976F));
                    builder.AddCubicBezier(new Vector2(5.44399977F, -1.29900002F), new Vector2(3.76200008F, -2.98200011F), new Vector2(1.68799996F, -2.98200011F));
                    builder.AddCubicBezier(new Vector2(1.68799996F, -2.98200011F), new Vector2(-1.68799996F, -2.98200011F), new Vector2(-1.68799996F, -2.98200011F));
                    builder.AddCubicBezier(new Vector2(-3.76300001F, -2.98200011F), new Vector2(-5.44399977F, -1.29900002F), new Vector2(-5.44399977F, 0.774999976F));
                    builder.AddCubicBezier(new Vector2(-5.44399977F, 0.774999976F), new Vector2(-5.44399977F, 2.98200011F), new Vector2(-5.44399977F, 2.98200011F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: edit-outline-top_s1g1_s2g2_s3g1_s4g2 Outlines
            // Offset:<11.104, -5.594>
            // - Path
            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(5.85599995F, 1.05400002F));
                    builder.AddCubicBezier(new Vector2(5.85599995F, 1.05400002F), new Vector2(5.4289999F, -1.11199999F), new Vector2(5.4289999F, -1.11199999F));
                    builder.AddCubicBezier(new Vector2(5.02799988F, -3.14700007F), new Vector2(3.05299997F, -4.47100019F), new Vector2(1.01800001F, -4.07000017F));
                    builder.AddCubicBezier(new Vector2(1.01800001F, -4.07000017F), new Vector2(-2.29399991F, -3.41700006F), new Vector2(-2.29399991F, -3.41700006F));
                    builder.AddCubicBezier(new Vector2(-4.32999992F, -3.01600003F), new Vector2(-5.65399981F, -1.03999996F), new Vector2(-5.25299978F, 0.995000005F));
                    builder.AddCubicBezier(new Vector2(-5.25299978F, 0.995000005F), new Vector2(-4.82600021F, 3.16000009F), new Vector2(-4.82600021F, 3.16000009F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: edit-outline-top_s1g1_s2g2_s3g1_s4g2 Outlines
            // Offset:<11.104, -5.594>
            // - Path
            CanvasGeometry Geometry_2()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(5.16300011F, 2.26699996F));
                    builder.AddCubicBezier(new Vector2(5.16300011F, 2.26699996F), new Vector2(5.55499983F, 0.0949999988F), new Vector2(5.55499983F, 0.0949999988F));
                    builder.AddCubicBezier(new Vector2(5.92299986F, -1.94599998F), new Vector2(4.56599998F, -3.90100002F), new Vector2(2.5250001F, -4.26900005F));
                    builder.AddCubicBezier(new Vector2(2.5250001F, -4.26900005F), new Vector2(-0.796999991F, -4.86800003F), new Vector2(-0.796999991F, -4.86800003F));
                    builder.AddCubicBezier(new Vector2(-2.83899999F, -5.23600006F), new Vector2(-4.79199982F, -3.87899995F), new Vector2(-5.15999985F, -1.83800006F));
                    builder.AddCubicBezier(new Vector2(-5.15999985F, -1.83800006F), new Vector2(-5.55200005F, 0.333999991F), new Vector2(-5.55200005F, 0.333999991F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - Layer aggregator
            // - - - Transforms: edit-outline-top_s1g1_s2g2_s3g1_s4g2 Outlines
            // Offset:<11.104, -5.594>
            // - Path
            CanvasGeometry Geometry_3()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(5.60200024F, -0.171000004F));
                    builder.AddCubicBezier(new Vector2(5.60200024F, -0.171000004F), new Vector2(5.17500019F, -2.33599997F), new Vector2(5.17500019F, -2.33599997F));
                    builder.AddCubicBezier(new Vector2(4.77400017F, -4.37099981F), new Vector2(2.7980001F, -5.69500017F), new Vector2(0.763000011F, -5.29400015F));
                    builder.AddCubicBezier(new Vector2(0.763000011F, -5.29400015F), new Vector2(-2.54900002F, -4.64099979F), new Vector2(-2.54900002F, -4.64099979F));
                    builder.AddCubicBezier(new Vector2(-4.58500004F, -4.23999977F), new Vector2(-5.90799999F, -2.2650001F), new Vector2(-5.50699997F, -0.230000004F));
                    builder.AddCubicBezier(new Vector2(-5.50699997F, -0.230000004F), new Vector2(-5.07999992F, 1.93599999F), new Vector2(-5.07999992F, 1.93599999F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - ShapeGroup: Group 2
            CanvasGeometry Geometry_4()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(16.4820004F, -0.00300000003F));
                    builder.AddCubicBezier(new Vector2(16.4820004F, 1.35500002F), new Vector2(15.2349997F, 2.45600009F), new Vector2(13.6949997F, 2.45700002F));
                    builder.AddLine(new Vector2(-13.6949997F, 2.46300006F));
                    builder.AddCubicBezier(new Vector2(-15.2349997F, 2.46300006F), new Vector2(-16.4820004F, 1.36199999F), new Vector2(-16.4820004F, 0.00300000003F));
                    builder.AddLine(new Vector2(-16.4820004F, -0.00300000003F));
                    builder.AddCubicBezier(new Vector2(-16.4820004F, -1.36099994F), new Vector2(-15.2340002F, -2.46300006F), new Vector2(-13.6949997F, -2.46300006F));
                    builder.AddLine(new Vector2(13.6949997F, -2.46300006F));
                    builder.AddCubicBezier(new Vector2(15.2340002F, -2.46300006F), new Vector2(16.4820004F, -1.36099994F), new Vector2(16.4820004F, -0.00300000003F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - ShapeGroup: Group 1 Offset:<21.483, 23.353>
            CanvasGeometry Geometry_5()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-13.5740004F, 5.45800018F));
                    builder.AddLine(new Vector2(-13.5740004F, -13.4259996F));
                    builder.AddLine(new Vector2(13.5740004F, -13.4259996F));
                    builder.AddLine(new Vector2(13.5740004F, 5.45800018F));
                    builder.AddCubicBezier(new Vector2(13.5740004F, 9.85900021F), new Vector2(10.0059996F, 13.4259996F), new Vector2(5.60500002F, 13.4259996F));
                    builder.AddLine(new Vector2(-5.60500002F, 13.4259996F));
                    builder.AddCubicBezier(new Vector2(-10.0059996F, 13.4259996F), new Vector2(-13.5740004F, 9.85900021F), new Vector2(-13.5740004F, 5.45800018F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - Transforms: edit-outline-top_s1g1_s2g2_s3g1_s4g1_background Outlines
            // Offset:<15.039, 14.37>
            CanvasGeometry Geometry_6()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-0.907999992F, -7.25899982F));
                    builder.AddLine(new Vector2(0.907999992F, 7.25899982F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - Transforms: edit-outline-top_s1g1_s2g2_s3g1_s4g1_background Outlines
            // Offset:<15.039, 14.37>
            CanvasGeometry Geometry_7()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(0.907999992F, -7.25899982F));
                    builder.AddLine(new Vector2(-0.907999992F, 7.25899982F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostLightPink_FFFF99A4()
            {
                return (_colorBrush_AlmostLightPink_FFFF99A4 == null)
                    ? _colorBrush_AlmostLightPink_FFFF99A4 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xFF, 0x99, 0xA4))
                    : _colorBrush_AlmostLightPink_FFFF99A4;
            }

            CompositionColorBrush ColorBrush_Black()
            {
                return (_colorBrush_Black == null)
                    ? _colorBrush_Black = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x00, 0x00, 0x00))
                    : _colorBrush_Black;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape()
            {
                if (_containerShape != null) { return _containerShape; }
                var result = _containerShape = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(21.4820004F, 20.8899994F);
                result.Offset = new Vector2(2.51799965F, 6.34100151F);
                var shapes = result.Shapes;
                // Transforms: edit-outline-top_s1g1_s2g2_s3g1_s4g2 Outlines Offset:<11.104, -5.594>
                shapes.Add(SpriteShape_0());
                // ShapeGroup: Group 2
                shapes.Add(SpriteShape_1());
                // ShapeGroup: Group 1 Offset:<21.483, 23.353>
                shapes.Add(SpriteShape_2());
                // Transforms: edit-outline-top_s1g1_s2g2_s3g1_s4g1_background Outlines
                // Offset:<15.039, 14.37>
                shapes.Add(SpriteShape_3());
                // Transforms: edit-outline-top_s1g1_s2g2_s3g1_s4g1_background Outlines
                // Offset:<15.039, 14.37>
                shapes.Add(SpriteShape_4());
                return result;
            }

            CompositionPath Path()
            {
                if (_path != null) { return _path; }
                var result = _path = new CompositionPath(Geometry_0());
                return result;
            }

            // - - Layer aggregator
            // Transforms: edit-outline-top_s1g1_s2g2_s3g1_s4g2 Outlines Offset:<11.104, -5.594>
            CompositionPathGeometry PathGeometry_0()
            {
                if (_pathGeometry_0 != null) { return _pathGeometry_0; }
                var result = _pathGeometry_0 = _c.CreatePathGeometry();
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Group 2
            CompositionPathGeometry PathGeometry_1()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_4()));
            }

            // - - Layer aggregator
            // ShapeGroup: Group 1 Offset:<21.483, 23.353>
            CompositionPathGeometry PathGeometry_2()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_5()));
            }

            // - - Layer aggregator
            // Transforms: edit-outline-top_s1g1_s2g2_s3g1_s4g1_background Outlines
            // Offset:<15.039, 14.37>
            CompositionPathGeometry PathGeometry_3()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_6()));
            }

            // - - Layer aggregator
            // Transforms: edit-outline-top_s1g1_s2g2_s3g1_s4g1_background Outlines
            // Offset:<15.039, 14.37>
            CompositionPathGeometry PathGeometry_4()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_7()));
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_0()
            {
                // Offset:<21.548, 2.388>
                var result = CreateSpriteShape(PathGeometry_0(), new Matrix3x2(1F, 0F, 0F, 1F, 21.5480003F, 2.38800001F));;
                result.StrokeBrush = ColorBrush_Black();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 0.920000017F;
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_1()
            {
                if (_spriteShape_1 != null) { return _spriteShape_1; }
                var result = _spriteShape_1 = _c.CreateSpriteShape(PathGeometry_1());
                result.FillBrush = ColorBrush_AlmostLightPink_FFFF99A4();
                result.StrokeBrush = ColorBrush_Black();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 0.920000017F;
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_2()
            {
                // Offset:<21.483, 23.353>
                var geometry = PathGeometry_2();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 21.4829998F, 23.3530006F), ColorBrush_AlmostLightPink_FFFF99A4());;
                result.StrokeBrush = ColorBrush_Black();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 0.920000017F;
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_3()
            {
                // Offset:<16.946999, 22.629>
                var result = CreateSpriteShape(PathGeometry_3(), new Matrix3x2(1F, 0F, 0F, 1F, 16.9469986F, 22.6289997F));;
                result.StrokeBrush = ColorBrush_Black();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 0.920000017F;
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_4()
            {
                // Offset:<26.456, 22.629>
                var result = CreateSpriteShape(PathGeometry_4(), new Matrix3x2(1F, 0F, 0F, 1F, 26.4559994F, 22.6289997F));;
                result.StrokeBrush = ColorBrush_Black();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 0.920000017F;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                propertySet.InsertScalar("t0", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            // - - - Layer aggregator
            // - Transforms: edit-outline-top_s1g1_s2g2_s3g1_s4g2 Outlines Offset:<11.104, -5.594>
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_0()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path(), HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.222222209F, new CompositionPath(Geometry_1()), CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertKeyFrame(0.444444418F, new CompositionPath(Geometry_2()), CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(0.666666627F, new CompositionPath(Geometry_3()), CubicBezierEasingFunction_0());
                // Frame 40.
                result.InsertKeyFrame(0.888888896F, Path(), CubicBezierEasingFunction_0());
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Group 2
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_0_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.222222209F, -8F, CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertKeyFrame(0.444444418F, 9F, CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(0.666666627F, -8F, CubicBezierEasingFunction_0());
                // Frame 40.
                result.InsertKeyFrame(0.888888896F, 0F, CubicBezierEasingFunction_0());
                return result;
            }

            // - Layer aggregator
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_0_1()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.222222209F, 10F, CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertKeyFrame(0.444444418F, -10F, CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(0.666666627F, 10F, CubicBezierEasingFunction_0());
                // Frame 40.
                result.InsertKeyFrame(0.888888896F, 0F, CubicBezierEasingFunction_0());
                return result;
            }

            ScalarKeyFrameAnimation t0ScalarAnimation_0_to_1()
            {
                // Frame 10.
                var result = CreateScalarKeyFrameAnimation(0.222222224F, 0F, StepThenHoldEasingFunction());
                result.SetReferenceParameter("_", _root);
                // Frame 20.
                result.InsertKeyFrame(0.444444388F, 1F, CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertKeyFrame(0.444444418F, 0F, StepThenHoldEasingFunction());
                // Frame 30.
                result.InsertKeyFrame(0.666666567F, 1F, CubicBezierEasingFunction_0());
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(48F, 48F);
                result.Shapes.Add(ContainerShape());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                if (_stepThenHoldEasingFunction != null) { return _stepThenHoldEasingFunction; }
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Group 2
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(21.4820004F, 7.33799982F), HoldThenStepEasingFunction());
                result.SetReferenceParameter("_", _root);
                // Frame 10.
                result.InsertKeyFrame(0.222222209F, new Vector2(21.4820004F, 4.85400009F), CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertExpressionKeyFrame(0.444444388F, "Pow(1-_.t0,3)*Vector2(21.482,4.854)+(3*Square(1-_.t0)*_.t0*Vector2(21.482,4.521))+(3*(1-_.t0)*Square(_.t0)*Vector2(21.482,5.338))+(Pow(_.t0,3)*Vector2(21.482,5.338))", StepThenHoldEasingFunction());
                // Frame 30.
                result.InsertExpressionKeyFrame(0.666666567F, "Pow(1-_.t0,3)*Vector2(21.482,5.338)+(3*Square(1-_.t0)*_.t0*Vector2(21.482,5.338))+(3*(1-_.t0)*Square(_.t0)*Vector2(21.482,4.521))+(Pow(_.t0,3)*Vector2(21.482,4.854))", StepThenHoldEasingFunction());
                // Frame 30.
                result.InsertKeyFrame(0.666666627F, new Vector2(21.4820004F, 4.85400009F), StepThenHoldEasingFunction());
                // Frame 40.
                result.InsertKeyFrame(0.888888896F, new Vector2(21.4820004F, 7.33799982F), CubicBezierEasingFunction_0());
                return result;
            }

            internal Delete_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(48F, 48F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _containerShape.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_0_1(), AnimationController_0());
                _pathGeometry_0.StartAnimation("Path", PathKeyFrameAnimation_0(), AnimationController_0());
                _spriteShape_1.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_0_0(), AnimationController_0());
                _spriteShape_1.StartAnimation("Offset", OffsetVector2Animation(), AnimationController_0());
                _root.Properties.StartAnimation("t0", t0ScalarAnimation_0_to_1(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _containerShape.StopAnimation("RotationAngleInDegrees");
                _pathGeometry_0.StopAnimation("Path");
                _spriteShape_1.StopAnimation("RotationAngleInDegrees");
                _spriteShape_1.StopAnimation("Offset");
                _root.Properties.StopAnimation("t0");
            }

        }
    }
}
