//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Namespace Starward.AnimatedVisuals -Public -WinUIVersion 3.0 -InputFile doodle-color-1821-moon-stars-hover-pinch.json
//       
//       Input file:
//           doodle-color-1821-moon-stars-hover-pinch.json (21558 bytes created 21:46+09:00 Aug 12 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |   142 |
// |--------------------------+-------|
// | Expression animators     |     1 |
// | KeyFrame animators       |    21 |
// | Reference parameters     |     1 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     3 |
// |--------------------------+-------|
// | ContainerVisuals         |     5 |
// | ShapeVisuals             |     5 |
// |--------------------------+-------|
// | ContainerShapes          |     5 |
// | CompositionSpriteShapes  |    11 |
// |--------------------------+-------|
// | Brushes                  |     2 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace Starward.AnimatedVisuals
{
    // Name:        doodle-color-225-night-sky-moon-stars
    // Frame rate:  60 fps
    // Frame count: 120
    // Duration:    2000.0 mS
    // _____________________________________________________________________________________________________________________________
    // |       Marker        |                        Constant                         |    Start     | Duration |    Progress     |
    // |                     |                       start | end                       |  Frame |  mS |       mS |     start | end |
    // |_____________________|_____________________________|___________________________|________|_____|__________|___________|_____|
    // | default:hover-pinch | M_default_hover_pinch_start | M_default_hover_pinch_end |    0.0 | 0.0 |   2000.0 | 0F        | 1d  |
    // -----------------------------------------------------------------------------------------------------------------------------
    public sealed class Doodle_color_1821_moon_stars_hover_pinch
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 2.000 seconds.
        internal const long c_durationTicks = 20000000;

        // Marker: default:hover-pinch.
        internal const float M_default_hover_pinch_start = 0F;

        // Marker: default:hover-pinch.
        internal const float M_default_hover_pinch_end = 1F;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new Doodle_color_1821_moon_stars_hover_pinch_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 120d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(20000000);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 120d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
                { "default:hover-pinch", 0d },
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class Doodle_color_1821_moon_stars_hover_pinch_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 20000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            BooleanKeyFrameAnimation _isVisibleBooleanAnimation;
            CompositionColorBrush _colorBrush_AlmostBlack_FF16161C;
            CompositionColorBrush _colorBrush_AlmostOrange_FFF9A708;
            CompositionContainerShape _containerShape_0;
            CompositionContainerShape _containerShape_1;
            CompositionContainerShape _containerShape_2;
            CompositionContainerShape _containerShape_3;
            CompositionContainerShape _containerShape_4;
            CompositionPath _path_0;
            CompositionPath _path_1;
            CompositionPath _path_2;
            CompositionPath _path_3;
            CompositionPath _path_4;
            CompositionPathGeometry _pathGeometry_3;
            CompositionPathGeometry _pathGeometry_4;
            CompositionPathGeometry _pathGeometry_5;
            CompositionPathGeometry _pathGeometry_6;
            CompositionPathGeometry _pathGeometry_7;
            CompositionPathGeometry _pathGeometry_8;
            CompositionSpriteShape _spriteShape_03;
            CompositionSpriteShape _spriteShape_04;
            ContainerVisual _containerVisual_1;
            ContainerVisual _containerVisual_2;
            ContainerVisual _containerVisual_3;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            CubicBezierEasingFunction _cubicBezierEasingFunction_2;
            InsetClip _insetClip_0;
            ScalarKeyFrameAnimation _rotationAngleInDegreesScalarAnimation_0_to_0_0;
            ScalarKeyFrameAnimation _rotationAngleInDegreesScalarAnimation_m50_to_50;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;
            Vector2KeyFrameAnimation _offsetVector2Animation;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            BooleanKeyFrameAnimation CreateBooleanKeyFrameAnimation(float initialProgress, bool initialValue)
            {
                var result = _c.CreateBooleanKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue);
                return result;
            }

            PathKeyFrameAnimation CreatePathKeyFrameAnimation(float initialProgress, CompositionPath initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreatePathKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            BooleanKeyFrameAnimation IsVisibleBooleanAnimation()
            {
                // Frame 0.
                if (_isVisibleBooleanAnimation != null) { return _isVisibleBooleanAnimation; }
                var result = _isVisibleBooleanAnimation = CreateBooleanKeyFrameAnimation(0F, false);
                // Frame 1.
                result.InsertKeyFrame(0.00833333377F, true);
                // Frame 22.
                result.InsertKeyFrame(0.183333337F, false);
                return result;
            }

            // - - - - - PreComp layer: hover-pinch
            // - - - - Layer aggregator
            // - - ShapeGroup: Vector
            CanvasGeometry Geometry_00()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-70.3929977F, -35.6829987F));
                    builder.AddCubicBezier(new Vector2(-61.7970009F, -55.026001F), new Vector2(-45.9570007F, -70.2269974F), new Vector2(-26.2759991F, -78.0199966F));
                    builder.AddCubicBezier(new Vector2(-26.2759991F, -78.0199966F), new Vector2(-44.8419991F, -21.809F), new Vector2(-23.7089996F, 13.1709995F));
                    builder.AddCubicBezier(new Vector2(5.19999981F, 61.0219994F), new Vector2(77.3710022F, 29.9850006F), new Vector2(77.3710022F, 29.9850006F));
                    builder.AddCubicBezier(new Vector2(59.2369995F, 70.7890015F), new Vector2(11.4589996F, 89.1660004F), new Vector2(-29.3439999F, 71.0329971F));
                    builder.AddCubicBezier(new Vector2(-70.1210022F, 52.9119987F), new Vector2(-88.5139999F, 5.09399986F), new Vector2(-70.3929977F, -35.6829987F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_01()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-70.0670013F, -111.947998F));
                    builder.AddCubicBezier(new Vector2(-89.6920013F, -99.572998F), new Vector2(-108.500999F, -72.3089981F), new Vector2(-99.0670013F, -31.698F));
                    builder.AddCubicBezier(new Vector2(-85.9420013F, 24.802F), new Vector2(-16.6930008F, 39.9269981F), new Vector2(35.3470001F, -6.34800005F));
                    builder.AddCubicBezier(new Vector2(9.68200016F, 4.55200005F), new Vector2(-7.94199991F, 3.05200005F), new Vector2(-26.0970001F, -1.82799995F));
                    builder.AddCubicBezier(new Vector2(-32.7639999F, -3.61999989F), new Vector2(-49.9710007F, -9.81999969F), new Vector2(-62.7459984F, -27.4440002F));
                    builder.AddCubicBezier(new Vector2(-74.3809967F, -43.4949989F), new Vector2(-82.6380005F, -68.8720016F), new Vector2(-70.0670013F, -111.947998F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_02()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(4.32399988F, -8.5369997F));
                    builder.AddCubicBezier(new Vector2(5.5250001F, -8.40799999F), new Vector2(13.802F, -12.7049999F), new Vector2(17.5979996F, -13.2189999F));
                    builder.AddCubicBezier(new Vector2(16.4470005F, -10.2360001F), new Vector2(10.96F, -3.08599997F), new Vector2(10.2030001F, -1.24199998F));
                    builder.AddCubicBezier(new Vector2(9.95499992F, -0.638000011F), new Vector2(17.4080009F, 7.21500015F), new Vector2(17.552F, 7.87699986F));
                    builder.AddCubicBezier(new Vector2(17.5699997F, 7.96199989F), new Vector2(6.70800018F, 4.61899996F), new Vector2(5.95699978F, 4.6869998F));
                    builder.AddCubicBezier(new Vector2(5.73699999F, 4.70699978F), new Vector2(-1.08500004F, 18.5580006F), new Vector2(-1.86000001F, 18.007F));
                    builder.AddCubicBezier(new Vector2(-3.29099989F, 16.9890003F), new Vector2(-1.83899999F, 3.0539999F), new Vector2(-2.46300006F, 2.95000005F));
                    builder.AddCubicBezier(new Vector2(-16.1100006F, 0.686999977F), new Vector2(-17.6110001F, -0.811999977F), new Vector2(-17.5979996F, -0.898000002F));
                    builder.AddCubicBezier(new Vector2(-17.3460007F, -2.54500008F), new Vector2(-2.98000002F, -5.16300011F), new Vector2(-2.92199993F, -5.70599985F));
                    builder.AddCubicBezier(new Vector2(-2.66599989F, -8.08399963F), new Vector2(-3.977F, -17.9799995F), new Vector2(-3.81999993F, -18.0189991F));
                    builder.AddCubicBezier(new Vector2(-2.89599991F, -18.2490005F), new Vector2(3.86400008F, -8.58600044F), new Vector2(4.32399988F, -8.5369997F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - PreComp layer: hover-pinch
            // - - - - Layer aggregator
            // - - - ShapeGroup: Vector
            // - Path
            CanvasGeometry Geometry_03()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(5.05600023F, -10.9250002F));
                    builder.AddCubicBezier(new Vector2(6.67799997F, -10.7510004F), new Vector2(17.8570004F, -16.5529995F), new Vector2(22.9839993F, -17.2479992F));
                    builder.AddCubicBezier(new Vector2(21.4300003F, -13.2189999F), new Vector2(14.0200005F, -3.56299996F), new Vector2(12.9969997F, -1.07299995F));
                    builder.AddCubicBezier(new Vector2(12.6619997F, -0.256999999F), new Vector2(22.7269993F, 10.349F), new Vector2(22.9220009F, 11.243F));
                    builder.AddCubicBezier(new Vector2(22.9459991F, 11.3570004F), new Vector2(8.27700043F, 6.84399986F), new Vector2(7.26200008F, 6.93599987F));
                    builder.AddCubicBezier(new Vector2(6.96500015F, 6.96299982F), new Vector2(-2.24900007F, 25.6700001F), new Vector2(-3.296F, 24.9249992F));
                    builder.AddCubicBezier(new Vector2(-5.22900009F, 23.5499992F), new Vector2(-3.26699996F, 4.72900009F), new Vector2(-4.11000013F, 4.58900023F));
                    builder.AddCubicBezier(new Vector2(-22.5410004F, 1.53299999F), new Vector2(-24.5680008F, -0.490999997F), new Vector2(-24.5499992F, -0.606999993F));
                    builder.AddCubicBezier(new Vector2(-24.2099991F, -2.83200002F), new Vector2(-4.80800009F, -6.36800003F), new Vector2(-4.72900009F, -7.10200024F));
                    builder.AddCubicBezier(new Vector2(-4.38399982F, -10.3140001F), new Vector2(-6.15399981F, -23.6779995F), new Vector2(-5.94199991F, -23.7310009F));
                    builder.AddCubicBezier(new Vector2(-4.69399977F, -24.0419998F), new Vector2(4.43499994F, -10.9919996F), new Vector2(5.05600023F, -10.9250002F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - PreComp layer: hover-pinch
            // - - - - Layer aggregator
            // - - - ShapeGroup: Vector
            // - Path
            CanvasGeometry Geometry_04()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(3.59500003F, -6.09700012F));
                    builder.AddCubicBezier(new Vector2(4.30700016F, -6.02099991F), new Vector2(12.4429998F, -11.1549997F), new Vector2(15.7340002F, -11.6009998F));
                    builder.AddCubicBezier(new Vector2(14.7360001F, -9.01500034F), new Vector2(7.52899981F, -2.86599994F), new Vector2(7.07999992F, -1.773F));
                    builder.AddCubicBezier(new Vector2(6.93300009F, -1.41499996F), new Vector2(15.5699997F, 6.11499977F), new Vector2(15.6949997F, 6.68900013F));
                    builder.AddCubicBezier(new Vector2(15.7110004F, 6.76200008F), new Vector2(5.0079999F, 1.70099998F), new Vector2(4.5630002F, 1.74100006F));
                    builder.AddCubicBezier(new Vector2(4.43300009F, 1.75300002F), new Vector2(-0.465000004F, 15.9510002F), new Vector2(-1.13699996F, 15.4729996F));
                    builder.AddCubicBezier(new Vector2(-2.37800002F, 14.5900002F), new Vector2(-0.0579999983F, 0.772000015F), new Vector2(-0.428000003F, 0.711000025F));
                    builder.AddCubicBezier(new Vector2(-8.51599979F, -0.629999995F), new Vector2(-14.7930002F, -0.843999982F), new Vector2(-14.7819996F, -0.917999983F));
                    builder.AddCubicBezier(new Vector2(-14.5640001F, -2.34599996F), new Vector2(-0.734000027F, -4.09700012F), new Vector2(-0.699000001F, -4.41900015F));
                    builder.AddCubicBezier(new Vector2(-0.547999978F, -5.82800007F), new Vector2(-2.97199988F, -15.7290001F), new Vector2(-2.83599997F, -15.7629995F));
                    builder.AddCubicBezier(new Vector2(-2.03500009F, -15.9619999F), new Vector2(3.32200003F, -6.12599993F), new Vector2(3.59500003F, -6.09700012F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_05()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(2.07299995F, -12.4379997F));
                    builder.AddCubicBezier(new Vector2(3.58599997F, -12.6059999F), new Vector2(12.5979996F, -20.1429996F), new Vector2(17.1280003F, -21.809F));
                    builder.AddCubicBezier(new Vector2(16.5249996F, -17.8260002F), new Vector2(11.7209997F, -7.53800011F), new Vector2(11.2910004F, -5.06400013F));
                    builder.AddCubicBezier(new Vector2(11.1499996F, -4.25299978F), new Vector2(22.4549999F, 3.37700009F), new Vector2(22.8129997F, 4.15199995F));
                    builder.AddCubicBezier(new Vector2(22.8579998F, 4.25099993F), new Vector2(8.58699989F, 3.09699988F), new Vector2(7.68100023F, 3.38499999F));
                    builder.AddCubicBezier(new Vector2(7.41599989F, 3.4690001F), new Vector2(2.79500008F, 22.3640003F), new Vector2(1.69099998F, 21.8969994F));
                    builder.AddCubicBezier(new Vector2(-0.347000003F, 21.0340004F), new Vector2(-2.35299993F, 3.49600005F), new Vector2(-3.14899993F, 3.53900003F));
                    builder.AddCubicBezier(new Vector2(-20.5510006F, 4.46999979F), new Vector2(-22.8050003F, 3.03500009F), new Vector2(-22.8120003F, 2.92600012F));
                    builder.AddCubicBezier(new Vector2(-22.9500008F, 0.83099997F), new Vector2(-5.9920001F, -6.30000019F), new Vector2(-6.06799984F, -6.98400021F));
                    builder.AddCubicBezier(new Vector2(-6.40100002F, -9.97900009F), new Vector2(-10.7060003F, -21.7929993F), new Vector2(-10.5240002F, -21.8840008F));
                    builder.AddCubicBezier(new Vector2(-9.44999981F, -22.4179993F), new Vector2(1.49399996F, -12.3739996F), new Vector2(2.07299995F, -12.4379997F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - PreComp layer: hover-pinch
            // - - - - Layer aggregator
            // - - - ShapeGroup: Vector
            // - Path
            CanvasGeometry Geometry_06()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(1.88499999F, -8.5F));
                    builder.AddCubicBezier(new Vector2(2.69000006F, -8.59000015F), new Vector2(9.97500038F, -16.3309994F), new Vector2(13.4300003F, -17.6019993F));
                    builder.AddCubicBezier(new Vector2(12.9700003F, -14.5640001F), new Vector2(7.02099991F, -5.8920002F), new Vector2(6.79199982F, -4.57499981F));
                    builder.AddCubicBezier(new Vector2(6.71700001F, -4.14300013F), new Vector2(17.4950008F, 1.61199999F), new Vector2(17.7679996F, 2.20300007F));
                    builder.AddCubicBezier(new Vector2(17.8029995F, 2.27900004F), new Vector2(5.35200024F, -0.230000004F), new Vector2(4.86999989F, -0.0769999996F));
                    builder.AddCubicBezier(new Vector2(4.72900009F, -0.0320000015F), new Vector2(2.49699998F, 16.0970001F), new Vector2(1.65499997F, 15.7399998F));
                    builder.AddCubicBezier(new Vector2(0.100000001F, 15.0819998F), new Vector2(-0.470999986F, -0.0179999992F), new Vector2(-0.894999981F, 0.00499999989F));
                    builder.AddCubicBezier(new Vector2(-10.158F, 0.500999987F), new Vector2(-17.0330009F, 1.35099995F), new Vector2(-17.0380001F, 1.26800001F));
                    builder.AddCubicBezier(new Vector2(-17.1439991F, -0.330000013F), new Vector2(-2.40899992F, -5.2329998F), new Vector2(-2.44899988F, -5.59700012F));
                    builder.AddCubicBezier(new Vector2(-2.62599993F, -7.19099998F), new Vector2(-7.80299997F, -17.5900002F), new Vector2(-7.66400003F, -17.6590004F));
                    builder.AddCubicBezier(new Vector2(-6.84499979F, -18.0669994F), new Vector2(1.57700002F, -8.4659996F), new Vector2(1.88499999F, -8.5F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - PreComp layer: hover-pinch
            // - - - - Layer aggregator
            // - - - ShapeGroup: Vector
            // - Path
            CanvasGeometry Geometry_07()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(2.2420001F, -14.2460003F));
                    builder.AddCubicBezier(new Vector2(4.046F, -14.4469995F), new Vector2(14.7950001F, -23.4360008F), new Vector2(20.1970005F, -25.4230003F));
                    builder.AddCubicBezier(new Vector2(19.4769993F, -20.6730003F), new Vector2(13.7480001F, -8.40299988F), new Vector2(13.2360001F, -5.45200014F));
                    builder.AddCubicBezier(new Vector2(13.0679998F, -4.48500013F), new Vector2(26.5510006F, 4.61600018F), new Vector2(26.9780006F, 5.53999996F));
                    builder.AddCubicBezier(new Vector2(27.0319996F, 5.65799999F), new Vector2(10.0109997F, 4.28100014F), new Vector2(8.93099976F, 4.625F));
                    builder.AddCubicBezier(new Vector2(8.61499977F, 4.7249999F), new Vector2(3.10299993F, 27.2600002F), new Vector2(1.78699994F, 26.7029991F));
                    builder.AddCubicBezier(new Vector2(-0.643999994F, 25.6739998F), new Vector2(-3.03699994F, 4.7579999F), new Vector2(-3.98600006F, 4.80900002F));
                    builder.AddCubicBezier(new Vector2(-24.7409992F, 5.91900015F), new Vector2(-27.4290009F, 4.20699978F), new Vector2(-27.4379997F, 4.07700014F));
                    builder.AddCubicBezier(new Vector2(-27.6030006F, 1.579F), new Vector2(-7.37699986F, -6.92500019F), new Vector2(-7.46799994F, -7.74100018F));
                    builder.AddCubicBezier(new Vector2(-7.86499977F, -11.3129997F), new Vector2(-13F, -25.4050007F), new Vector2(-12.7819996F, -25.5130005F));
                    builder.AddCubicBezier(new Vector2(-11.5019999F, -26.1499996F), new Vector2(1.551F, -14.1689997F), new Vector2(2.2420001F, -14.2460003F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_08()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-0.188999996F, -0.0359999985F));
                    builder.AddCubicBezier(new Vector2(-0.187000006F, -0.0359999985F), new Vector2(-0.231000006F, -0.0410000011F), new Vector2(-0.238999993F, 0.00200000009F));
                    builder.AddCubicBezier(new Vector2(-0.238999993F, -0.0280000009F), new Vector2(-0.254000008F, -0.0390000008F), new Vector2(-0.27700001F, -0.0469999984F));
                    builder.AddCubicBezier(new Vector2(-0.277999997F, -0.0469999984F), new Vector2(-0.238000005F, -0.0460000001F), new Vector2(-0.228F, -0.0839999989F));
                    builder.AddCubicBezier(new Vector2(-0.228F, -0.0850000009F), new Vector2(-0.231999993F, -0.0450000018F), new Vector2(-0.188999996F, -0.0359999985F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - Path
            CanvasGeometry Geometry_09()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-8.88300037F, -1.12600005F));
                    builder.AddCubicBezier(new Vector2(-9.35900021F, -1.22099996F), new Vector2(-0.345999986F, -0.263999999F), new Vector2(1.17900002F, -8.73499966F));
                    builder.AddCubicBezier(new Vector2(1.16700006F, -2.73699999F), new Vector2(4.15700006F, -0.467000008F), new Vector2(8.65799999F, 1.07799995F));
                    builder.AddCubicBezier(new Vector2(8.89299965F, 1.15900004F), new Vector2(0.876999974F, 0.991999984F), new Vector2(-1.08000004F, 8.49400043F));
                    builder.AddCubicBezier(new Vector2(-1.13900006F, 8.71700001F), new Vector2(-0.375999987F, 0.578999996F), new Vector2(-8.88300037F, -1.12600005F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_10()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(140.468002F, 99.7809982F));
                    builder.AddCubicBezier(new Vector2(139.468002F, 102.280998F), new Vector2(131.218002F, 127.780998F), new Vector2(103.218002F, 136.531006F));
                    builder.AddCubicBezier(new Vector2(32.762001F, 158.548004F), new Vector2(-5.53200006F, 123.030998F), new Vector2(-17.5319996F, 96.2809982F));
                    builder.AddCubicBezier(new Vector2(-28.9869995F, 70.7460022F), new Vector2(-24.6089993F, 38.6930008F), new Vector2(-19.3339996F, 22.0720005F));
                    builder.AddCubicBezier(new Vector2(-14.059F, 5.45100021F), new Vector2(-2.62700009F, -11.7489996F), new Vector2(19.3339996F, -22.0720005F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostBlack_FF16161C()
            {
                return (_colorBrush_AlmostBlack_FF16161C == null)
                    ? _colorBrush_AlmostBlack_FF16161C = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x16, 0x16, 0x1C))
                    : _colorBrush_AlmostBlack_FF16161C;
            }

            CompositionColorBrush ColorBrush_AlmostOrange_FFF9A708()
            {
                return (_colorBrush_AlmostOrange_FFF9A708 == null)
                    ? _colorBrush_AlmostOrange_FFF9A708 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xF9, 0xA7, 0x08))
                    : _colorBrush_AlmostOrange_FFF9A708;
            }

            // - PreComp layer: hover-pinch
            // Layer aggregator
            CompositionContainerShape ContainerShape_0()
            {
                if (_containerShape_0 != null) { return _containerShape_0; }
                var result = _containerShape_0 = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // ShapeGroup: Vector
                shapes.Add(SpriteShape_00());
                // Transforms: line Offset:<32.551, 46.512>
                shapes.Add(SpriteShape_01());
                // Transforms: line Offset:<32.551, 46.512>
                shapes.Add(SpriteShape_02());
                return result;
            }

            // - - PreComp layer: hover-pinch
            // - PreComp layer: star
            // Shape tree root for layer: Vector 21
            CompositionContainerShape ContainerShape_1()
            {
                if (_containerShape_1 != null) { return _containerShape_1; }
                var result = _containerShape_1 = _c.CreateContainerShape();
                result.Offset = new Vector2(16.0090008F, 15.9239998F);
                // ShapeGroup: Vector RotationDegrees:-7.436999797821045
                result.Shapes.Add(SpriteShape_05());
                return result;
            }

            // - - PreComp layer: hover-pinch
            // - PreComp layer: star
            // Shape tree root for layer: Vector 21
            CompositionContainerShape ContainerShape_2()
            {
                if (_containerShape_2 != null) { return _containerShape_2; }
                var result = _containerShape_2 = _c.CreateContainerShape();
                result.Offset = new Vector2(16.0090008F, 15.9239998F);
                // ShapeGroup: Vector RotationDegrees:-7.436999797821045
                result.Shapes.Add(SpriteShape_06());
                return result;
            }

            // - - PreComp layer: hover-pinch
            // - PreComp layer: star
            // Shape tree root for layer: Vector 21
            CompositionContainerShape ContainerShape_3()
            {
                if (_containerShape_3 != null) { return _containerShape_3; }
                var result = _containerShape_3 = _c.CreateContainerShape();
                result.Offset = new Vector2(16.0090008F, 15.9239998F);
                // ShapeGroup: Vector RotationDegrees:-7.436999797821045
                result.Shapes.Add(SpriteShape_07());
                return result;
            }

            // - PreComp layer: hover-pinch
            // Layer aggregator
            CompositionContainerShape ContainerShape_4()
            {
                if (_containerShape_4 != null) { return _containerShape_4; }
                var result = _containerShape_4 = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // Transforms: line 2 Offset:<-60.609, -58.343>
                shapes.Add(SpriteShape_08());
                // Transforms: line 3 Offset:<-60.609, -58.343>
                shapes.Add(SpriteShape_09());
                // Transforms: line 4 Offset:<-60.609, -58.343>
                shapes.Add(SpriteShape_10());
                return result;
            }

            CompositionPath Path_0()
            {
                if (_path_0 != null) { return _path_0; }
                var result = _path_0 = new CompositionPath(Geometry_01());
                return result;
            }

            CompositionPath Path_1()
            {
                if (_path_1 != null) { return _path_1; }
                var result = _path_1 = new CompositionPath(Geometry_02());
                return result;
            }

            CompositionPath Path_2()
            {
                if (_path_2 != null) { return _path_2; }
                var result = _path_2 = new CompositionPath(Geometry_05());
                return result;
            }

            CompositionPath Path_3()
            {
                if (_path_3 != null) { return _path_3; }
                var result = _path_3 = new CompositionPath(Geometry_08());
                return result;
            }

            CompositionPath Path_4()
            {
                if (_path_4 != null) { return _path_4; }
                var result = _path_4 = new CompositionPath(Geometry_10());
                return result;
            }

            // - - - PreComp layer: hover-pinch
            // - - Layer aggregator
            // ShapeGroup: Vector
            CompositionPathGeometry PathGeometry_0()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_00()));
            }

            // - - - PreComp layer: hover-pinch
            // - - Layer aggregator
            // Transforms: line Offset:<32.551, 46.512>
            CompositionPathGeometry PathGeometry_1()
            {
                var result = _c.CreatePathGeometry(Path_0());
                result.TrimEnd = 0.31400001F;
                result.TrimStart = 0.0900000036F;
                return result;
            }

            // - - - PreComp layer: hover-pinch
            // - - Layer aggregator
            // Transforms: line Offset:<32.551, 46.512>
            CompositionPathGeometry PathGeometry_2()
            {
                var result = _c.CreatePathGeometry(Path_0());
                result.TrimEnd = 0.30399999F;
                result.TrimOffset = 0.394444436F;
                result.TrimStart = 0.201000005F;
                return result;
            }

            // - - PreComp layer: hover-pinch
            // - Layer aggregator
            // ShapeGroup: Vector
            CompositionPathGeometry PathGeometry_3()
            {
                if (_pathGeometry_3 != null) { return _pathGeometry_3; }
                var result = _pathGeometry_3 = _c.CreatePathGeometry();
                return result;
            }

            // - - PreComp layer: hover-pinch
            // - Layer aggregator
            // ShapeGroup: Vector
            CompositionPathGeometry PathGeometry_4()
            {
                if (_pathGeometry_4 != null) { return _pathGeometry_4; }
                var result = _pathGeometry_4 = _c.CreatePathGeometry();
                return result;
            }

            CompositionPathGeometry PathGeometry_5()
            {
                if (_pathGeometry_5 != null) { return _pathGeometry_5; }
                var result = _pathGeometry_5 = _c.CreatePathGeometry();
                return result;
            }

            // - - - PreComp layer: hover-pinch
            // - - Layer aggregator
            // Transforms: line 2 Offset:<-60.609, -58.343>
            CompositionPathGeometry PathGeometry_6()
            {
                if (_pathGeometry_6 != null) { return _pathGeometry_6; }
                var result = _pathGeometry_6 = _c.CreatePathGeometry(Path_4());
                return result;
            }

            // - - - PreComp layer: hover-pinch
            // - - Layer aggregator
            // Transforms: line 3 Offset:<-60.609, -58.343>
            CompositionPathGeometry PathGeometry_7()
            {
                if (_pathGeometry_7 != null) { return _pathGeometry_7; }
                var result = _pathGeometry_7 = _c.CreatePathGeometry(Path_4());
                result.TrimOffset = -0.413888901F;
                return result;
            }

            // - - - PreComp layer: hover-pinch
            // - - Layer aggregator
            // Transforms: line 4 Offset:<-60.609, -58.343>
            CompositionPathGeometry PathGeometry_8()
            {
                if (_pathGeometry_8 != null) { return _pathGeometry_8; }
                var result = _pathGeometry_8 = _c.CreatePathGeometry(Path_4());
                result.TrimOffset = -0.836111128F;
                return result;
            }

            // - - PreComp layer: hover-pinch
            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_00()
            {
                var result = _c.CreateSpriteShape(PathGeometry_0());
                result.FillBrush = ColorBrush_AlmostOrange_FFF9A708();
                result.StrokeBrush = ColorBrush_AlmostOrange_FFF9A708();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                return result;
            }

            // - - PreComp layer: hover-pinch
            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_01()
            {
                // Offset:<32.551, 46.512>
                var result = CreateSpriteShape(PathGeometry_1(), new Matrix3x2(1F, 0F, 0F, 1F, 32.5509987F, 46.512001F));;
                result.StrokeBrush = ColorBrush_AlmostBlack_FF16161C();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeDashOffset = -52F;
                var strokeDashArray = result.StrokeDashArray;
                strokeDashArray.Add(52F);
                strokeDashArray.Add(10F);
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 2F;
                return result;
            }

            // - - PreComp layer: hover-pinch
            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_02()
            {
                // Offset:<32.551, 46.512>
                var result = CreateSpriteShape(PathGeometry_2(), new Matrix3x2(1F, 0F, 0F, 1F, 32.5509987F, 46.512001F));;
                result.StrokeBrush = ColorBrush_AlmostBlack_FF16161C();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 2F;
                return result;
            }

            // - PreComp layer: hover-pinch
            // Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_03()
            {
                if (_spriteShape_03 != null) { return _spriteShape_03; }
                var result = _spriteShape_03 = _c.CreateSpriteShape(PathGeometry_3());
                result.CenterPoint = new Vector2(2.75F, -1.5F);
                result.Offset = new Vector2(152.016006F, 38.9760017F);
                result.FillBrush = ColorBrush_AlmostOrange_FFF9A708();
                result.StrokeBrush = ColorBrush_AlmostBlack_FF16161C();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 1.99899995F;
                return result;
            }

            // - PreComp layer: hover-pinch
            // Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_04()
            {
                if (_spriteShape_04 != null) { return _spriteShape_04; }
                var result = _spriteShape_04 = _c.CreateSpriteShape(PathGeometry_4());
                result.CenterPoint = new Vector2(1.5F, -3.25F);
                result.Offset = new Vector2(125.212997F, 97.3170013F);
                result.FillBrush = ColorBrush_AlmostOrange_FFF9A708();
                result.StrokeBrush = ColorBrush_AlmostBlack_FF16161C();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 1.99699998F;
                return result;
            }

            // - - - PreComp layer: hover-pinch
            // - - PreComp layer: star
            // - Shape tree root for layer: Vector 21
            // Path 1
            CompositionSpriteShape SpriteShape_05()
            {
                // Rotation:-7.436997977847751 degrees, Scale:<0.99999994, 0.99999994>
                var geometry = PathGeometry_5();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0.991587758F, -0.129435956F, 0.129435956F, 0.991587758F, 0F, 0F), ColorBrush_AlmostOrange_FFF9A708());;
                result.StrokeBrush = ColorBrush_AlmostBlack_FF16161C();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 2F;
                return result;
            }

            // - - - PreComp layer: hover-pinch
            // - - PreComp layer: star
            // - Shape tree root for layer: Vector 21
            // Path 1
            CompositionSpriteShape SpriteShape_06()
            {
                // Rotation:-7.436997977847751 degrees, Scale:<0.99999994, 0.99999994>
                var geometry = PathGeometry_5();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0.991587758F, -0.129435956F, 0.129435956F, 0.991587758F, 0F, 0F), ColorBrush_AlmostOrange_FFF9A708());;
                result.StrokeBrush = ColorBrush_AlmostBlack_FF16161C();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 2F;
                return result;
            }

            // - - - PreComp layer: hover-pinch
            // - - PreComp layer: star
            // - Shape tree root for layer: Vector 21
            // Path 1
            CompositionSpriteShape SpriteShape_07()
            {
                // Rotation:-7.436997977847751 degrees, Scale:<0.99999994, 0.99999994>
                var geometry = PathGeometry_5();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0.991587758F, -0.129435956F, 0.129435956F, 0.991587758F, 0F, 0F), ColorBrush_AlmostOrange_FFF9A708());;
                result.StrokeBrush = ColorBrush_AlmostBlack_FF16161C();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 2F;
                return result;
            }

            // - - PreComp layer: hover-pinch
            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_08()
            {
                // Offset:<-60.609, -58.343>
                var result = CreateSpriteShape(PathGeometry_6(), new Matrix3x2(1F, 0F, 0F, 1F, -60.6090012F, -58.3429985F));;
                result.StrokeBrush = ColorBrush_AlmostBlack_FF16161C();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 2F;
                return result;
            }

            // - - PreComp layer: hover-pinch
            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_09()
            {
                // Offset:<-60.609, -58.343>
                var result = CreateSpriteShape(PathGeometry_7(), new Matrix3x2(1F, 0F, 0F, 1F, -60.6090012F, -58.3429985F));;
                result.StrokeBrush = ColorBrush_AlmostBlack_FF16161C();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 2F;
                return result;
            }

            // - - PreComp layer: hover-pinch
            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_10()
            {
                // Offset:<-60.609, -58.343>
                var result = CreateSpriteShape(PathGeometry_8(), new Matrix3x2(1F, 0F, 0F, 1F, -60.6090012F, -58.3429985F));;
                result.StrokeBrush = ColorBrush_AlmostBlack_FF16161C();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 2F;
                return result;
            }

            // Transforms for hover-pinch Scale(1,1,0)
            ContainerVisual ContainerVisual_0()
            {
                var result = _c.CreateContainerVisual();
                result.Clip = InsetClip_0();
                result.Size = new Vector2(192F, 192F);
                // Scale:<1, 1>
                result.TransformMatrix = new Matrix4x4(1F, 0F, 0F, 0F, 0F, 1F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 1F);
                var children = result.Children;
                // Layer aggregator
                children.InsertAtTop(ShapeVisual_0());
                // PreComp layer: star
                children.InsertAtTop(ContainerVisual_1());
                // PreComp layer: star
                children.InsertAtTop(ContainerVisual_2());
                // PreComp layer: star
                children.InsertAtTop(ContainerVisual_3());
                // Layer aggregator
                children.InsertAtTop(ShapeVisual_4());
                return result;
            }

            // PreComp layer: hover-pinch
            // Transforms for star Scale(1,1,0), RotationDegrees(28), Offset(7.125,4.75,0)
            ContainerVisual ContainerVisual_1()
            {
                if (_containerVisual_1 != null) { return _containerVisual_1; }
                var result = _containerVisual_1 = _c.CreateContainerVisual();
                result.Clip = InsetClip_0();
                result.IsVisible = false;
                result.Size = new Vector2(32F, 32F);
                // Offset:<16.509384, -0.8887062>, Rotation:{X:0 Y:0 Z:0.24192192 W:0.9702957},
                // Scale:<0.99999994, 0.99999994>
                result.TransformMatrix = new Matrix4x4(0.882947564F, 0.469471574F, 0F, 0F, -0.469471574F, 0.882947564F, 0F, 0F, 0F, 0F, 0F, 0F, 16.5093842F, -0.888706207F, 0F, 1F);
                // Shape tree root for layer: Vector 21
                result.Children.InsertAtTop(ShapeVisual_1());
                return result;
            }

            // PreComp layer: hover-pinch
            // Transforms for star Scale(1,1,0), RotationDegrees(26), Offset(82.125,33.25,0)
            ContainerVisual ContainerVisual_2()
            {
                if (_containerVisual_2 != null) { return _containerVisual_2; }
                var result = _containerVisual_2 = _c.CreateContainerVisual();
                result.Clip = InsetClip_0();
                result.IsVisible = false;
                result.Size = new Vector2(32F, 32F);
                // Offset:<90.75823, 27.855356>, Rotation:{X:0 Y:0 Z:0.22495106 W:0.97437006},
                // Scale:<1, 1>
                result.TransformMatrix = new Matrix4x4(0.898794055F, 0.438371152F, 0F, 0F, -0.438371152F, 0.898794055F, 0F, 0F, 0F, 0F, 0F, 0F, 90.7582321F, 27.8553562F, 0F, 1F);
                // Shape tree root for layer: Vector 21
                result.Children.InsertAtTop(ShapeVisual_2());
                return result;
            }

            // PreComp layer: hover-pinch
            // Transforms for star Scale(1,1,0), RotationDegrees(10), Offset(7.875,148.5,0)
            ContainerVisual ContainerVisual_3()
            {
                if (_containerVisual_3 != null) { return _containerVisual_3; }
                var result = _containerVisual_3 = _c.CreateContainerVisual();
                result.Clip = InsetClip_0();
                result.IsVisible = false;
                result.Size = new Vector2(32F, 32F);
                // Offset:<10.896447, 145.9647>, Rotation:{X:0 Y:0 Z:0.08715575 W:0.9961947},
                // Scale:<0.99999994, 0.99999994>
                result.TransformMatrix = new Matrix4x4(0.98480773F, 0.173648179F, 0F, 0F, -0.173648179F, 0.98480773F, 0F, 0F, 0F, 0F, 0F, 0F, 10.8964472F, 145.964706F, 0F, 1F);
                // Shape tree root for layer: Vector 21
                result.Children.InsertAtTop(ShapeVisual_3());
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // PreComp layer: hover-pinch
                result.Children.InsertAtTop(ContainerVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return (_cubicBezierEasingFunction_1 == null)
                    ? _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.479999989F, 1F))
                    : _cubicBezierEasingFunction_1;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_2()
            {
                return (_cubicBezierEasingFunction_2 == null)
                    ? _cubicBezierEasingFunction_2 = _c.CreateCubicBezierEasingFunction(new Vector2(0.519999981F, 0F), new Vector2(0.479999989F, 1F))
                    : _cubicBezierEasingFunction_2;
            }

            InsetClip InsetClip_0()
            {
                if (_insetClip_0 != null) { return _insetClip_0; }
                var result = _insetClip_0 = _c.CreateInsetClip();
                return result;
            }

            // - - - PreComp layer: hover-pinch
            // - - Layer aggregator
            // - ShapeGroup: Vector
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_0()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_1(), StepThenHoldEasingFunction());
                // Frame 6.
                result.InsertKeyFrame(0.0500000007F, Path_1(), HoldThenStepEasingFunction());
                // Frame 22.
                result.InsertKeyFrame(0.183333337F, new CompositionPath(Geometry_03()), CubicBezierEasingFunction_0());
                // Frame 60.
                result.InsertKeyFrame(0.5F, new CompositionPath(Geometry_04()), CubicBezierEasingFunction_0());
                // Frame 86.
                result.InsertKeyFrame(0.716666639F, Path_1(), CubicBezierEasingFunction_0());
                return result;
            }

            // - - - PreComp layer: hover-pinch
            // - - Layer aggregator
            // - ShapeGroup: Vector
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_1()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_2(), HoldThenStepEasingFunction());
                // Frame 26.
                result.InsertKeyFrame(0.216666669F, new CompositionPath(Geometry_06()), CubicBezierEasingFunction_0());
                // Frame 69.
                result.InsertKeyFrame(0.574999988F, new CompositionPath(Geometry_07()), CubicBezierEasingFunction_0());
                // Frame 120.
                result.InsertKeyFrame(1F, Path_2(), CubicBezierEasingFunction_0());
                return result;
            }

            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_2()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_3(), HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.0833333358F, new CompositionPath(Geometry_09()), _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.150000006F, 1F)));
                // Frame 21.
                result.InsertKeyFrame(0.174999997F, Path_3(), _c.CreateCubicBezierEasingFunction(new Vector2(0.850000024F, 0F), new Vector2(0.833000004F, 0.833000004F)));
                return result;
            }

            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_0_0()
            {
                // Frame 0.
                if (_rotationAngleInDegreesScalarAnimation_0_to_0_0 != null) { return _rotationAngleInDegreesScalarAnimation_0_to_0_0; }
                var result = _rotationAngleInDegreesScalarAnimation_0_to_0_0 = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 39.
                result.InsertKeyFrame(0.324999988F, -5F, CubicBezierEasingFunction_0());
                // Frame 74.
                result.InsertKeyFrame(0.616666675F, 0F, _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.389999986F, 1F)));
                return result;
            }

            // - - PreComp layer: hover-pinch
            // - Layer aggregator
            // ShapeGroup: Vector
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_0_1()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 12.
                result.InsertKeyFrame(0.100000001F, 0F, HoldThenStepEasingFunction());
                // Frame 41.
                result.InsertKeyFrame(0.341666669F, -33F, _c.CreateCubicBezierEasingFunction(new Vector2(0.518999994F, 0F), new Vector2(0.666999996F, 1F)));
                // Frame 101.
                result.InsertKeyFrame(0.841666639F, 0F, _c.CreateCubicBezierEasingFunction(new Vector2(0.160999998F, 0F), new Vector2(0.293000013F, 1F)));
                return result;
            }

            // - - PreComp layer: hover-pinch
            // - Layer aggregator
            // ShapeGroup: Vector
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_0_2()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 12.
                result.InsertKeyFrame(0.100000001F, 0F, HoldThenStepEasingFunction());
                // Frame 47.
                result.InsertKeyFrame(0.391666681F, 63F, _c.CreateCubicBezierEasingFunction(new Vector2(0.488000005F, 0F), new Vector2(0.666999996F, 1F)));
                // Frame 112.
                result.InsertKeyFrame(0.933333337F, 0F, _c.CreateCubicBezierEasingFunction(new Vector2(0.179000005F, 0F), new Vector2(0.275999993F, 1F)));
                return result;
            }

            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_m50_to_50()
            {
                // Frame 0.
                if (_rotationAngleInDegreesScalarAnimation_m50_to_50 != null) { return _rotationAngleInDegreesScalarAnimation_m50_to_50; }
                var result = _rotationAngleInDegreesScalarAnimation_m50_to_50 = CreateScalarKeyFrameAnimation(0F, -50F, HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.0833333358F, 0F, _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.666999996F, 1F)));
                // Frame 21.
                result.InsertKeyFrame(0.174999997F, 50F, _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.833000004F, 0.833000004F)));
                return result;
            }

            // - - - - PreComp layer: hover-pinch
            // - - - Layer aggregator
            // - Transforms: line 2 Offset:<-60.609, -58.343>
            // TrimEnd
            ScalarKeyFrameAnimation TrimEndScalarAnimation_1_to_1_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 1F, HoldThenStepEasingFunction());
                // Frame 57.
                result.InsertKeyFrame(0.474999994F, 0.860000014F, CubicBezierEasingFunction_1());
                // Frame 90.
                result.InsertKeyFrame(0.75F, 1F, CubicBezierEasingFunction_2());
                return result;
            }

            // - - - - PreComp layer: hover-pinch
            // - - - Layer aggregator
            // - Transforms: line 3 Offset:<-60.609, -58.343>
            // TrimEnd
            ScalarKeyFrameAnimation TrimEndScalarAnimation_1_to_1_1()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 1F, HoldThenStepEasingFunction());
                // Frame 41.
                result.InsertKeyFrame(0.341666669F, 0.889999986F, CubicBezierEasingFunction_1());
                // Frame 90.
                result.InsertKeyFrame(0.75F, 1F, CubicBezierEasingFunction_2());
                return result;
            }

            // - - - - PreComp layer: hover-pinch
            // - - - Layer aggregator
            // - Transforms: line 4 Offset:<-60.609, -58.343>
            // TrimEnd
            ScalarKeyFrameAnimation TrimEndScalarAnimation_1_to_1_2()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 1F, HoldThenStepEasingFunction());
                // Frame 50.
                result.InsertKeyFrame(0.416666657F, 0.920000017F, CubicBezierEasingFunction_1());
                // Frame 90.
                result.InsertKeyFrame(0.75F, 1F, CubicBezierEasingFunction_2());
                return result;
            }

            // - - - - PreComp layer: hover-pinch
            // - - - Layer aggregator
            // - Transforms: line 3 Offset:<-60.609, -58.343>
            // TrimStart
            ScalarKeyFrameAnimation TrimStartScalarAnimation_0p89_to_0p89()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0.889999986F, HoldThenStepEasingFunction());
                // Frame 41.
                result.InsertKeyFrame(0.341666669F, 0.75F, CubicBezierEasingFunction_1());
                // Frame 90.
                result.InsertKeyFrame(0.75F, 0.889999986F, CubicBezierEasingFunction_2());
                return result;
            }

            // - - - - PreComp layer: hover-pinch
            // - - - Layer aggregator
            // - Transforms: line 2 Offset:<-60.609, -58.343>
            // TrimStart
            ScalarKeyFrameAnimation TrimStartScalarAnimation_0p816_to_0p816()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0.815999985F, HoldThenStepEasingFunction());
                // Frame 57.
                result.InsertKeyFrame(0.474999994F, 0.68599999F, CubicBezierEasingFunction_1());
                // Frame 90.
                result.InsertKeyFrame(0.75F, 0.815999985F, CubicBezierEasingFunction_2());
                return result;
            }

            // - - - - PreComp layer: hover-pinch
            // - - - Layer aggregator
            // - Transforms: line 4 Offset:<-60.609, -58.343>
            // TrimStart
            ScalarKeyFrameAnimation TrimStartScalarAnimation_0p857_to_0p857()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0.856999993F, HoldThenStepEasingFunction());
                // Frame 50.
                result.InsertKeyFrame(0.416666657F, 0.876999974F, CubicBezierEasingFunction_1());
                // Frame 90.
                result.InsertKeyFrame(0.75F, 0.856999993F, CubicBezierEasingFunction_2());
                return result;
            }

            // PreComp layer: hover-pinch
            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(192F, 192F);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_0());
                // ShapeGroup: Vector
                shapes.Add(SpriteShape_03());
                // ShapeGroup: Vector
                shapes.Add(SpriteShape_04());
                return result;
            }

            // - PreComp layer: hover-pinch
            // PreComp layer: star
            // Shape tree root for layer: Vector 21
            ShapeVisual ShapeVisual_1()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(32F, 32F);
                result.Shapes.Add(ContainerShape_1());
                return result;
            }

            // - PreComp layer: hover-pinch
            // PreComp layer: star
            // Shape tree root for layer: Vector 21
            ShapeVisual ShapeVisual_2()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(32F, 32F);
                result.Shapes.Add(ContainerShape_2());
                return result;
            }

            // - PreComp layer: hover-pinch
            // PreComp layer: star
            // Shape tree root for layer: Vector 21
            ShapeVisual ShapeVisual_3()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(32F, 32F);
                result.Shapes.Add(ContainerShape_3());
                return result;
            }

            // PreComp layer: hover-pinch
            // Layer aggregator
            ShapeVisual ShapeVisual_4()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(192F, 192F);
                result.Shapes.Add(ContainerShape_4());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                if (_stepThenHoldEasingFunction != null) { return _stepThenHoldEasingFunction; }
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation()
            {
                // Frame 0.
                if (_offsetVector2Animation != null) { return _offsetVector2Animation; }
                var result = _offsetVector2Animation = CreateVector2KeyFrameAnimation(0F, new Vector2(98.1409988F, 97.5619965F), HoldThenStepEasingFunction());
                // Frame 23.
                result.InsertKeyFrame(0.191666663F, new Vector2(98.1409988F, 105.061996F), _c.CreateCubicBezierEasingFunction(new Vector2(0.442999989F, 0F), new Vector2(0.388000011F, 1F)));
                // Frame 60.
                result.InsertKeyFrame(0.5F, new Vector2(98.1409988F, 97.5619965F), _c.CreateCubicBezierEasingFunction(new Vector2(0.546000004F, 0F), new Vector2(0.363000005F, 1F)));
                return result;
            }

            internal Doodle_color_1821_moon_stars_hover_pinch_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(192F, 192F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _containerShape_0.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_0_0(), AnimationController_0());
                _containerShape_0.StartAnimation("Offset", OffsetVector2Animation(), AnimationController_0());
                _containerShape_1.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_m50_to_50(), AnimationController_0());
                _containerShape_2.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_m50_to_50(), AnimationController_0());
                _containerShape_3.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_m50_to_50(), AnimationController_0());
                _containerShape_4.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_0_0(), AnimationController_0());
                _containerShape_4.StartAnimation("Offset", OffsetVector2Animation(), AnimationController_0());
                _pathGeometry_3.StartAnimation("Path", PathKeyFrameAnimation_0(), AnimationController_0());
                _pathGeometry_4.StartAnimation("Path", PathKeyFrameAnimation_1(), AnimationController_0());
                _pathGeometry_5.StartAnimation("Path", PathKeyFrameAnimation_2(), AnimationController_0());
                _pathGeometry_6.StartAnimation("TrimStart", TrimStartScalarAnimation_0p816_to_0p816(), AnimationController_0());
                _pathGeometry_6.StartAnimation("TrimEnd", TrimEndScalarAnimation_1_to_1_0(), AnimationController_0());
                _pathGeometry_7.StartAnimation("TrimStart", TrimStartScalarAnimation_0p89_to_0p89(), AnimationController_0());
                _pathGeometry_7.StartAnimation("TrimEnd", TrimEndScalarAnimation_1_to_1_1(), AnimationController_0());
                _pathGeometry_8.StartAnimation("TrimStart", TrimStartScalarAnimation_0p857_to_0p857(), AnimationController_0());
                _pathGeometry_8.StartAnimation("TrimEnd", TrimEndScalarAnimation_1_to_1_2(), AnimationController_0());
                _spriteShape_03.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_0_1(), AnimationController_0());
                _spriteShape_04.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_0_2(), AnimationController_0());
                _containerVisual_1.StartAnimation("IsVisible", IsVisibleBooleanAnimation(), AnimationController_0());
                _containerVisual_2.StartAnimation("IsVisible", IsVisibleBooleanAnimation(), AnimationController_0());
                _containerVisual_3.StartAnimation("IsVisible", IsVisibleBooleanAnimation(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _containerShape_0.StopAnimation("RotationAngleInDegrees");
                _containerShape_0.StopAnimation("Offset");
                _containerShape_1.StopAnimation("RotationAngleInDegrees");
                _containerShape_2.StopAnimation("RotationAngleInDegrees");
                _containerShape_3.StopAnimation("RotationAngleInDegrees");
                _containerShape_4.StopAnimation("RotationAngleInDegrees");
                _containerShape_4.StopAnimation("Offset");
                _pathGeometry_3.StopAnimation("Path");
                _pathGeometry_4.StopAnimation("Path");
                _pathGeometry_5.StopAnimation("Path");
                _pathGeometry_6.StopAnimation("TrimStart");
                _pathGeometry_6.StopAnimation("TrimEnd");
                _pathGeometry_7.StopAnimation("TrimStart");
                _pathGeometry_7.StopAnimation("TrimEnd");
                _pathGeometry_8.StopAnimation("TrimStart");
                _pathGeometry_8.StopAnimation("TrimEnd");
                _spriteShape_03.StopAnimation("RotationAngleInDegrees");
                _spriteShape_04.StopAnimation("RotationAngleInDegrees");
                _containerVisual_1.StopAnimation("IsVisible");
                _containerVisual_2.StopAnimation("IsVisible");
                _containerVisual_3.StopAnimation("IsVisible");
            }

        }
    }
}
