//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Namespace Starward.AnimatedVisuals -Public -WinUIVersion 3.0 -InputFile download.json
//       
//       Input file:
//           download.json (13254 bytes created 21:55+09:00 Aug 13 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |   102 |
// |--------------------------+-------|
// | Expression animators     |     1 |
// | KeyFrame animators       |     7 |
// | Reference parameters     |     1 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     5 |
// | ShapeVisuals             |     5 |
// |--------------------------+-------|
// | ContainerShapes          |     7 |
// | CompositionSpriteShapes  |    10 |
// |--------------------------+-------|
// | Brushes                  |     8 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     4 |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas;
using Microsoft.Graphics.Canvas.Effects;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace Starward.AnimatedVisuals
{
    // Name:        download
    // Frame rate:  29.9700012207031 fps
    // Frame count: 44.0000017921567
    // Duration:    1468.1 mS
    public sealed class Download
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 1.468 seconds.
        internal const long c_durationTicks = 14681348;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new Download_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 44.0000017921567;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 29.9700012207031;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(14681348);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 44.0000017921567;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class Download_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 14681348;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionColorBrush _colorBrush_AlmostMediumSeaGreen_FF6CCB5F;
            CompositionColorBrush _colorBrush_Black;
            CompositionContainerShape _containerShape_0;
            CompositionContainerShape _containerShape_1;
            CompositionContainerShape _containerShape_2;
            CompositionContainerShape _containerShape_3;
            CompositionContainerShape _containerShape_4;
            CompositionContainerShape _containerShape_5;
            CompositionContainerShape _containerShape_6;
            CompositionEffectFactory _effectFactory;
            CompositionPathGeometry _pathGeometry_0;
            CompositionPathGeometry _pathGeometry_1;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            StepEasingFunction _holdThenStepEasingFunction;
            Vector2KeyFrameAnimation _offsetVector2Animation_0;
            Vector2KeyFrameAnimation _offsetVector2Animation_1;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-15.7270002F, 7.98999977F));
                    builder.AddLine(new Vector2(-15.7270002F, -7.98999977F));
                    builder.AddCubicBezier(new Vector2(-15.7270002F, -12.2629995F), new Vector2(-12.2629995F, -15.7270002F), new Vector2(-7.98999977F, -15.7270002F));
                    builder.AddLine(new Vector2(7.98999977F, -15.7270002F));
                    builder.AddCubicBezier(new Vector2(12.2629995F, -15.7270002F), new Vector2(15.7279997F, -12.2629995F), new Vector2(15.7279997F, -7.98999977F));
                    builder.AddLine(new Vector2(15.7279997F, 7.98999977F));
                    builder.AddCubicBezier(new Vector2(15.7279997F, 12.2629995F), new Vector2(12.2629995F, 15.7270002F), new Vector2(7.98999977F, 15.7270002F));
                    builder.AddLine(new Vector2(-7.98999977F, 15.7270002F));
                    builder.AddCubicBezier(new Vector2(-12.2629995F, 15.7270002F), new Vector2(-15.7270002F, 12.2629995F), new Vector2(-15.7270002F, 7.98999977F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(7.66099977F, -3.83100009F));
                    builder.AddLine(new Vector2(0F, 3.83100009F));
                    builder.AddLine(new Vector2(-7.66099977F, -3.83100009F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    builder.BeginFigure(new Vector2(0F, 3.83100009F));
                    builder.AddLine(new Vector2(0F, -10.1689997F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostMediumSeaGreen_FF6CCB5F()
            {
                return (_colorBrush_AlmostMediumSeaGreen_FF6CCB5F == null)
                    ? _colorBrush_AlmostMediumSeaGreen_FF6CCB5F = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x6C, 0xCB, 0x5F))
                    : _colorBrush_AlmostMediumSeaGreen_FF6CCB5F;
            }

            CompositionColorBrush ColorBrush_Black()
            {
                return (_colorBrush_Black == null)
                    ? _colorBrush_Black = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x00, 0x00, 0x00))
                    : _colorBrush_Black;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_0()
            {
                if (_containerShape_0 != null) { return _containerShape_0; }
                var result = _containerShape_0 = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // ShapeGroup: Group 1 Offset:<20.727, 20.727>
                shapes.Add(SpriteShape_0());
                // ShapeGroup: Group 1 Offset:<20.727, 20.727>
                shapes.Add(SpriteShape_1());
                return result;
            }

            // Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines
            CompositionContainerShape ContainerShape_1()
            {
                if (_containerShape_1 != null) { return _containerShape_1; }
                var result = _containerShape_1 = _c.CreateContainerShape();
                // Transforms: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines
                result.Shapes.Add(ContainerShape_2());
                return result;
            }

            // - Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines
            // Transforms for download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines
            CompositionContainerShape ContainerShape_2()
            {
                if (_containerShape_2 != null) { return _containerShape_2; }
                var result = _containerShape_2 = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // ShapeGroup: Group 1 Offset:<12.661, 15.17>
                shapes.Add(SpriteShape_2());
                // ShapeGroup: Group 2 Offset:<12.661, -11.83>
                shapes.Add(SpriteShape_3());
                // ShapeGroup: Group 3 Offset:<12.661, -37.83>
                shapes.Add(SpriteShape_4());
                return result;
            }

            // Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1_background
            // Outlines 2
            CompositionContainerShape ContainerShape_3()
            {
                if (_containerShape_3 != null) { return _containerShape_3; }
                var result = _containerShape_3 = _c.CreateContainerShape();
                // Transforms: download-outline-bot_s1g1_s2g2_s3g1_s4g1_background Outlines 2
                result.Shapes.Add(SpriteShape_5());
                return result;
            }

            // Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines 2
            CompositionContainerShape ContainerShape_4()
            {
                if (_containerShape_4 != null) { return _containerShape_4; }
                var result = _containerShape_4 = _c.CreateContainerShape();
                // Transforms: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines 2
                result.Shapes.Add(ContainerShape_5());
                return result;
            }

            // - Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines 2
            // Transforms for download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines 2
            CompositionContainerShape ContainerShape_5()
            {
                if (_containerShape_5 != null) { return _containerShape_5; }
                var result = _containerShape_5 = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // ShapeGroup: Group 1 Offset:<12.661, 15.17>
                shapes.Add(SpriteShape_6());
                // ShapeGroup: Group 2 Offset:<12.661, -11.83>
                shapes.Add(SpriteShape_7());
                // ShapeGroup: Group 3 Offset:<12.661, -37.83>
                shapes.Add(SpriteShape_8());
                return result;
            }

            // Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1_background
            // Outlines 4
            CompositionContainerShape ContainerShape_6()
            {
                if (_containerShape_6 != null) { return _containerShape_6; }
                var result = _containerShape_6 = _c.CreateContainerShape();
                // Transforms: download-outline-bot_s1g1_s2g2_s3g1_s4g1_background Outlines 4
                result.Shapes.Add(SpriteShape_9());
                return result;
            }

            CompositionEffectBrush EffectBrush_0()
            {
                var effectFactory = EffectFactory();
                var result = effectFactory.CreateBrush();
                result.SetSourceParameter("destination", SurfaceBrush_0());
                result.SetSourceParameter("source", SurfaceBrush_1());
                return result;
            }

            CompositionEffectBrush EffectBrush_1()
            {
                var effectFactory = EffectFactory();
                var result = effectFactory.CreateBrush();
                result.SetSourceParameter("destination", SurfaceBrush_2());
                result.SetSourceParameter("source", SurfaceBrush_3());
                return result;
            }

            CompositionEffectFactory EffectFactory()
            {
                var compositeEffect = new CompositeEffect();
                compositeEffect.Mode = CanvasComposite.DestinationIn;
                compositeEffect.Sources.Add(new CompositionEffectSourceParameter("destination"));
                compositeEffect.Sources.Add(new CompositionEffectSourceParameter("source"));
                if (_effectFactory != null) { return _effectFactory; }
                var result = _effectFactory = _c.CreateEffectFactory(compositeEffect);
                return result;
            }

            CompositionPathGeometry PathGeometry_0()
            {
                return (_pathGeometry_0 == null)
                    ? _pathGeometry_0 = _c.CreatePathGeometry(new CompositionPath(Geometry_0()))
                    : _pathGeometry_0;
            }

            CompositionPathGeometry PathGeometry_1()
            {
                return (_pathGeometry_1 == null)
                    ? _pathGeometry_1 = _c.CreatePathGeometry(new CompositionPath(Geometry_1()))
                    : _pathGeometry_1;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_0()
            {
                // Offset:<20.727, 20.727>
                var geometry = PathGeometry_0();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 20.7269993F, 20.7269993F), ColorBrush_AlmostMediumSeaGreen_FF6CCB5F());;
                result.StrokeBrush = ColorBrush_Black();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 0.920000017F;
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_1()
            {
                // Offset:<20.727, 20.727>
                var geometry = PathGeometry_0();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 20.7269993F, 20.7269993F), ColorBrush_AlmostMediumSeaGreen_FF6CCB5F());;
                result.StrokeBrush = ColorBrush_Black();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 0.920000017F;
                return result;
            }

            // - - Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines
            // Transforms: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines
            // ShapeGroup: Group 1 Offset:<12.661, 15.17>
            CompositionSpriteShape SpriteShape_2()
            {
                // Offset:<12.661, 15.17>
                var result = CreateSpriteShape(PathGeometry_1(), new Matrix3x2(1F, 0F, 0F, 1F, 12.6610003F, 15.1700001F));;
                result.StrokeBrush = ColorBrush_Black();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 0.920000017F;
                return result;
            }

            // - - Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines
            // Transforms: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines
            // ShapeGroup: Group 2 Offset:<12.661, -11.83>
            CompositionSpriteShape SpriteShape_3()
            {
                // Offset:<12.661, -11.83>
                var result = CreateSpriteShape(PathGeometry_1(), new Matrix3x2(1F, 0F, 0F, 1F, 12.6610003F, -11.8299999F));;
                result.StrokeBrush = ColorBrush_Black();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 0.920000017F;
                return result;
            }

            // - - Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines
            // Transforms: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines
            // ShapeGroup: Group 3 Offset:<12.661, -37.83>
            CompositionSpriteShape SpriteShape_4()
            {
                // Offset:<12.661, -37.83>
                var result = CreateSpriteShape(PathGeometry_1(), new Matrix3x2(1F, 0F, 0F, 1F, 12.6610003F, -37.8300018F));;
                result.StrokeBrush = ColorBrush_Black();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 0.920000017F;
                return result;
            }

            // - Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1_background
            // Outlines 2
            // Path 1
            CompositionSpriteShape SpriteShape_5()
            {
                // Offset:<20.727, 20.727>
                var geometry = PathGeometry_0();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 20.7269993F, 20.7269993F), ColorBrush_AlmostMediumSeaGreen_FF6CCB5F());;
                return result;
            }

            // - - Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines 2
            // Transforms: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines 2
            // ShapeGroup: Group 1 Offset:<12.661, 15.17>
            CompositionSpriteShape SpriteShape_6()
            {
                // Offset:<12.661, 15.17>
                var result = CreateSpriteShape(PathGeometry_1(), new Matrix3x2(1F, 0F, 0F, 1F, 12.6610003F, 15.1700001F));;
                result.StrokeBrush = ColorBrush_Black();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 0.920000017F;
                return result;
            }

            // - - Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines 2
            // Transforms: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines 2
            // ShapeGroup: Group 2 Offset:<12.661, -11.83>
            CompositionSpriteShape SpriteShape_7()
            {
                // Offset:<12.661, -11.83>
                var result = CreateSpriteShape(PathGeometry_1(), new Matrix3x2(1F, 0F, 0F, 1F, 12.6610003F, -11.8299999F));;
                result.StrokeBrush = ColorBrush_Black();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 0.920000017F;
                return result;
            }

            // - - Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines 2
            // Transforms: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines 2
            // ShapeGroup: Group 3 Offset:<12.661, -37.83>
            CompositionSpriteShape SpriteShape_8()
            {
                // Offset:<12.661, -37.83>
                var result = CreateSpriteShape(PathGeometry_1(), new Matrix3x2(1F, 0F, 0F, 1F, 12.6610003F, -37.8300018F));;
                result.StrokeBrush = ColorBrush_Black();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 0.920000017F;
                return result;
            }

            // - Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1_background
            // Outlines 4
            // Path 1
            CompositionSpriteShape SpriteShape_9()
            {
                // Offset:<20.727, 20.727>
                var geometry = PathGeometry_0();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 20.7269993F, 20.7269993F), ColorBrush_AlmostMediumSeaGreen_FF6CCB5F());;
                return result;
            }

            CompositionSurfaceBrush SurfaceBrush_0()
            {
                return _c.CreateSurfaceBrush(VisualSurface_0());
            }

            CompositionSurfaceBrush SurfaceBrush_1()
            {
                return _c.CreateSurfaceBrush(VisualSurface_1());
            }

            CompositionSurfaceBrush SurfaceBrush_2()
            {
                return _c.CreateSurfaceBrush(VisualSurface_2());
            }

            CompositionSurfaceBrush SurfaceBrush_3()
            {
                return _c.CreateSurfaceBrush(VisualSurface_3());
            }

            CompositionVisualSurface VisualSurface_0()
            {
                var result = _c.CreateVisualSurface();
                result.SourceVisual = ContainerVisual_0();
                result.SourceSize = new Vector2(48F, 48F);
                return result;
            }

            CompositionVisualSurface VisualSurface_1()
            {
                var result = _c.CreateVisualSurface();
                result.SourceVisual = ContainerVisual_1();
                result.SourceSize = new Vector2(48F, 48F);
                return result;
            }

            CompositionVisualSurface VisualSurface_2()
            {
                var result = _c.CreateVisualSurface();
                result.SourceVisual = ContainerVisual_2();
                result.SourceSize = new Vector2(48F, 48F);
                return result;
            }

            CompositionVisualSurface VisualSurface_3()
            {
                var result = _c.CreateVisualSurface();
                result.SourceVisual = ContainerVisual_3();
                result.SourceSize = new Vector2(48F, 48F);
                return result;
            }

            ContainerVisual ContainerVisual_0()
            {
                var result = _c.CreateContainerVisual();
                result.BorderMode = CompositionBorderMode.Soft;
                // Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines
                result.Children.InsertAtTop(ShapeVisual_1());
                return result;
            }

            ContainerVisual ContainerVisual_1()
            {
                var result = _c.CreateContainerVisual();
                result.BorderMode = CompositionBorderMode.Soft;
                // Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1_background
                // Outlines 2
                result.Children.InsertAtTop(ShapeVisual_2());
                return result;
            }

            ContainerVisual ContainerVisual_2()
            {
                var result = _c.CreateContainerVisual();
                result.BorderMode = CompositionBorderMode.Soft;
                // Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines 2
                result.Children.InsertAtTop(ShapeVisual_3());
                return result;
            }

            ContainerVisual ContainerVisual_3()
            {
                var result = _c.CreateContainerVisual();
                result.BorderMode = CompositionBorderMode.Soft;
                // Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1_background
                // Outlines 4
                result.Children.InsertAtTop(ShapeVisual_4());
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                var children = result.Children;
                // Layer aggregator
                children.InsertAtTop(ShapeVisual_0());
                children.InsertAtTop(SpriteVisual_0());
                children.InsertAtTop(SpriteVisual_1());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(48F, 48F);
                result.Shapes.Add(ContainerShape_0());
                return result;
            }

            // Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines
            ShapeVisual ShapeVisual_1()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(48F, 48F);
                result.Shapes.Add(ContainerShape_1());
                return result;
            }

            // Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1_background
            // Outlines 2
            ShapeVisual ShapeVisual_2()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(48F, 48F);
                result.Shapes.Add(ContainerShape_3());
                return result;
            }

            // Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1 Outlines 2
            ShapeVisual ShapeVisual_3()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(48F, 48F);
                result.Shapes.Add(ContainerShape_4());
                return result;
            }

            // Shape tree root for layer: download-outline-bot_s1g1_s2g2_s3g1_s4g1_background
            // Outlines 4
            ShapeVisual ShapeVisual_4()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(48F, 48F);
                result.Shapes.Add(ContainerShape_6());
                return result;
            }

            SpriteVisual SpriteVisual_0()
            {
                var result = _c.CreateSpriteVisual();
                result.Size = new Vector2(48F, 48F);
                result.Brush = EffectBrush_0();
                return result;
            }

            SpriteVisual SpriteVisual_1()
            {
                var result = _c.CreateSpriteVisual();
                result.Size = new Vector2(48F, 48F);
                result.Brush = EffectBrush_1();
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_0()
            {
                // Frame 0.
                if (_offsetVector2Animation_0 != null) { return _offsetVector2Animation_0; }
                var result = _offsetVector2Animation_0 = CreateVector2KeyFrameAnimation(0F, new Vector2(3.27200007F, 2.773F), HoldThenStepEasingFunction());
                // Frame 22.
                result.InsertKeyFrame(0.49999997F, new Vector2(3.27200007F, 3.773F), CubicBezierEasingFunction_0());
                // Frame 44.
                result.InsertKeyFrame(1F, new Vector2(3.27200007F, 2.773F), _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 1F)));
                return result;
            }

            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_1()
            {
                // Frame 0.
                if (_offsetVector2Animation_1 != null) { return _offsetVector2Animation_1; }
                var result = _offsetVector2Animation_1 = CreateVector2KeyFrameAnimation(0F, new Vector2(8.06599998F, 8.72700024F), HoldThenStepEasingFunction());
                // Frame 44.
                result.InsertKeyFrame(1F, new Vector2(8.06599998F, 61.7270012F), CubicBezierEasingFunction_0());
                return result;
            }

            internal Download_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(48F, 48F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _containerShape_0.StartAnimation("Offset", OffsetVector2Animation_0(), AnimationController_0());
                _containerShape_1.StartAnimation("Offset", OffsetVector2Animation_0(), AnimationController_0());
                _containerShape_2.StartAnimation("Offset", OffsetVector2Animation_1(), AnimationController_0());
                _containerShape_3.StartAnimation("Offset", OffsetVector2Animation_0(), AnimationController_0());
                _containerShape_4.StartAnimation("Offset", OffsetVector2Animation_0(), AnimationController_0());
                _containerShape_5.StartAnimation("Offset", OffsetVector2Animation_1(), AnimationController_0());
                _containerShape_6.StartAnimation("Offset", OffsetVector2Animation_0(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _containerShape_0.StopAnimation("Offset");
                _containerShape_1.StopAnimation("Offset");
                _containerShape_2.StopAnimation("Offset");
                _containerShape_3.StopAnimation("Offset");
                _containerShape_4.StopAnimation("Offset");
                _containerShape_5.StopAnimation("Offset");
                _containerShape_6.StopAnimation("Offset");
            }

        }
    }
}
