//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Namespace Starward.AnimatedVisuals -Public -WinUIVersion 3.0 -InputFile wired-lineal-37-check-hover-wobble.json
//       
//       Input file:
//           wired-lineal-37-check-hover-wobble.json (12075 bytes created 21:50+09:00 Aug 12 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    44 |
// |--------------------------+-------|
// | Expression animators     |     1 |
// | KeyFrame animators       |     3 |
// | Reference parameters     |     1 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     3 |
// |--------------------------+-------|
// | ContainerVisuals         |     2 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     - |
// | CompositionSpriteShapes  |     3 |
// |--------------------------+-------|
// | Brushes                  |     3 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace Starward.AnimatedVisuals
{
    // Name:        wired-lineal-37-approve-checked-simple
    // Frame rate:  60 fps
    // Frame count: 60
    // Duration:    1000.0 mS
    // ________________________________________________________________________________________________________________________________
    // |        Marker        |                         Constant                          |    Start     | Duration |    Progress     |
    // |                      |                        start | end                        |  Frame |  mS |       mS |     start | end |
    // |______________________|______________________________|____________________________|________|_____|__________|___________|_____|
    // | default:hover-wobble | M_default_hover_wobble_start | M_default_hover_wobble_end |    0.0 | 0.0 |   1000.0 | 0F        | 1d  |
    // --------------------------------------------------------------------------------------------------------------------------------
    public sealed class Wired_lineal_37_check_hover_wobble
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 1.000 seconds.
        internal const long c_durationTicks = 10000000;

        // Marker: default:hover-wobble.
        internal const float M_default_hover_wobble_start = 0F;

        // Marker: default:hover-wobble.
        internal const float M_default_hover_wobble_end = 1F;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new Wired_lineal_37_check_hover_wobble_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 60d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(10000000);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 60d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
                { "default:hover-wobble", 0d },
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class Wired_lineal_37_check_hover_wobble_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 10000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionPath _path_0;
            CompositionPath _path_1;
            CompositionPath _path_2;
            CompositionPathGeometry _pathGeometry_0;
            CompositionPathGeometry _pathGeometry_1;
            CompositionPathGeometry _pathGeometry_2;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            CubicBezierEasingFunction _cubicBezierEasingFunction_2;
            StepEasingFunction _holdThenStepEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            PathKeyFrameAnimation CreatePathKeyFrameAnimation(float initialProgress, CompositionPath initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreatePathKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            CanvasGeometry Geometry_00()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(129.473999F, -142.908997F));
                    builder.AddCubicBezier(new Vector2(128.302002F, -144.080994F), new Vector2(126.403999F, -144.080994F), new Vector2(125.232002F, -142.908997F));
                    builder.AddCubicBezier(new Vector2(125.232002F, -142.908997F), new Vector2(-42.5F, 24.8220005F), new Vector2(-42.5F, 24.8220005F));
                    builder.AddCubicBezier(new Vector2(-42.5F, 24.8220005F), new Vector2(-125.231003F, -57.9090004F), new Vector2(-125.231003F, -57.9090004F));
                    builder.AddCubicBezier(new Vector2(-126.403F, -59.0810013F), new Vector2(-128.302002F, -59.0810013F), new Vector2(-129.473999F, -57.9090004F));
                    builder.AddCubicBezier(new Vector2(-129.473999F, -57.9090004F), new Vector2(-185.335999F, -2.0480001F), new Vector2(-185.335999F, -2.0480001F));
                    builder.AddCubicBezier(new Vector2(-186.507996F, -0.875999987F), new Vector2(-186.507996F, 1.023F), new Vector2(-185.335999F, 2.19499993F));
                    builder.AddCubicBezier(new Vector2(-185.335999F, 2.19499993F), new Vector2(-44.6209984F, 142.908997F), new Vector2(-44.6209984F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-43.4490013F, 144.080994F), new Vector2(-41.5509987F, 144.080994F), new Vector2(-40.3790016F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-40.3790016F, 142.908997F), new Vector2(185.335999F, -82.8050003F), new Vector2(185.335999F, -82.8050003F));
                    builder.AddCubicBezier(new Vector2(186.507996F, -83.9769974F), new Vector2(186.507996F, -85.8759995F), new Vector2(185.335999F, -87.0479965F));
                    builder.AddCubicBezier(new Vector2(185.335999F, -87.0479965F), new Vector2(129.473999F, -142.908997F), new Vector2(129.473999F, -142.908997F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - PreComp layer: hover-wobble
            // - - - - Layer aggregator
            // - - -  Offset:<217.457, 210.03>
            // - Path
            CanvasGeometry Geometry_01()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(89.473999F, -102.908997F));
                    builder.AddCubicBezier(new Vector2(88.302002F, -104.081001F), new Vector2(86.4039993F, -104.081001F), new Vector2(85.2320023F, -102.908997F));
                    builder.AddCubicBezier(new Vector2(85.2320023F, -102.908997F), new Vector2(-42.5F, 24.8220005F), new Vector2(-42.5F, 24.8220005F));
                    builder.AddCubicBezier(new Vector2(-42.5F, 24.8220005F), new Vector2(-145.231995F, -77.9089966F), new Vector2(-145.231995F, -77.9089966F));
                    builder.AddCubicBezier(new Vector2(-146.404007F, -79.0810013F), new Vector2(-148.302002F, -79.0810013F), new Vector2(-149.473999F, -77.9089966F));
                    builder.AddCubicBezier(new Vector2(-149.473999F, -77.9089966F), new Vector2(-205.335999F, -22.0480003F), new Vector2(-205.335999F, -22.0480003F));
                    builder.AddCubicBezier(new Vector2(-206.507996F, -20.8759995F), new Vector2(-206.507996F, -18.9769993F), new Vector2(-205.335999F, -17.8050003F));
                    builder.AddCubicBezier(new Vector2(-205.335999F, -17.8050003F), new Vector2(-44.6209984F, 142.908997F), new Vector2(-44.6209984F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-43.4490013F, 144.080994F), new Vector2(-41.5509987F, 144.080994F), new Vector2(-40.3790016F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-40.3790016F, 142.908997F), new Vector2(145.335999F, -42.8050003F), new Vector2(145.335999F, -42.8050003F));
                    builder.AddCubicBezier(new Vector2(146.507996F, -43.9770012F), new Vector2(146.507996F, -45.8759995F), new Vector2(145.335999F, -47.0480003F));
                    builder.AddCubicBezier(new Vector2(145.335999F, -47.0480003F), new Vector2(89.473999F, -102.908997F), new Vector2(89.473999F, -102.908997F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - PreComp layer: hover-wobble
            // - - - - Layer aggregator
            // - - -  Offset:<217.457, 210.03>
            // - Path
            CanvasGeometry Geometry_02()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(149.473999F, -162.908997F));
                    builder.AddCubicBezier(new Vector2(148.302002F, -164.080994F), new Vector2(146.404007F, -164.080994F), new Vector2(145.231995F, -162.908997F));
                    builder.AddCubicBezier(new Vector2(145.231995F, -162.908997F), new Vector2(-42.5F, 24.8220005F), new Vector2(-42.5F, 24.8220005F));
                    builder.AddCubicBezier(new Vector2(-42.5F, 24.8220005F), new Vector2(-95.2310028F, -27.9090004F), new Vector2(-95.2310028F, -27.9090004F));
                    builder.AddCubicBezier(new Vector2(-96.4029999F, -29.0809994F), new Vector2(-98.302002F, -29.0809994F), new Vector2(-99.473999F, -27.9090004F));
                    builder.AddCubicBezier(new Vector2(-99.473999F, -27.9090004F), new Vector2(-155.335999F, 27.9519997F), new Vector2(-155.335999F, 27.9519997F));
                    builder.AddCubicBezier(new Vector2(-156.507996F, 29.1240005F), new Vector2(-156.507996F, 31.0230007F), new Vector2(-155.335999F, 32.1949997F));
                    builder.AddCubicBezier(new Vector2(-155.335999F, 32.1949997F), new Vector2(-44.6209984F, 142.908997F), new Vector2(-44.6209984F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-43.4490013F, 144.080994F), new Vector2(-41.5509987F, 144.080994F), new Vector2(-40.3790016F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-40.3790016F, 142.908997F), new Vector2(205.335999F, -102.805F), new Vector2(205.335999F, -102.805F));
                    builder.AddCubicBezier(new Vector2(206.507996F, -103.976997F), new Vector2(206.507996F, -105.875999F), new Vector2(205.335999F, -107.047997F));
                    builder.AddCubicBezier(new Vector2(205.335999F, -107.047997F), new Vector2(149.473999F, -162.908997F), new Vector2(149.473999F, -162.908997F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - PreComp layer: hover-wobble
            // - - - - Layer aggregator
            // - - -  Offset:<217.457, 210.03>
            // - Path
            CanvasGeometry Geometry_03()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(119.704002F, -133.139008F));
                    builder.AddCubicBezier(new Vector2(118.531998F, -134.311005F), new Vector2(116.633003F, -134.311005F), new Vector2(115.460999F, -133.139008F));
                    builder.AddCubicBezier(new Vector2(115.460999F, -133.139008F), new Vector2(-42.5F, 24.8220005F), new Vector2(-42.5F, 24.8220005F));
                    builder.AddCubicBezier(new Vector2(-42.5F, 24.8220005F), new Vector2(-129.886993F, -62.5649986F), new Vector2(-129.886993F, -62.5649986F));
                    builder.AddCubicBezier(new Vector2(-131.059006F, -63.7369995F), new Vector2(-132.957993F, -63.7369995F), new Vector2(-134.130005F, -62.5649986F));
                    builder.AddCubicBezier(new Vector2(-134.130005F, -62.5649986F), new Vector2(-189.990997F, -6.70300007F), new Vector2(-189.990997F, -6.70300007F));
                    builder.AddCubicBezier(new Vector2(-191.162994F, -5.53100014F), new Vector2(-191.162994F, -3.6329999F), new Vector2(-189.990997F, -2.46099997F));
                    builder.AddCubicBezier(new Vector2(-189.990997F, -2.46099997F), new Vector2(-44.6209984F, 142.908997F), new Vector2(-44.6209984F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-43.4490013F, 144.080994F), new Vector2(-41.5509987F, 144.080994F), new Vector2(-40.3790016F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-40.3790016F, 142.908997F), new Vector2(175.565002F, -73.0350037F), new Vector2(175.565002F, -73.0350037F));
                    builder.AddCubicBezier(new Vector2(176.737F, -74.2070007F), new Vector2(176.737F, -76.1050034F), new Vector2(175.565002F, -77.2770004F));
                    builder.AddCubicBezier(new Vector2(175.565002F, -77.2770004F), new Vector2(119.704002F, -133.139008F), new Vector2(119.704002F, -133.139008F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - PreComp layer: hover-wobble
            // - - - - Layer aggregator
            // - - -  Offset:<217.457, 210.03>
            // - Path
            CanvasGeometry Geometry_04()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(139.703995F, -153.139008F));
                    builder.AddCubicBezier(new Vector2(138.531998F, -154.311005F), new Vector2(136.632996F, -154.311005F), new Vector2(135.460999F, -153.139008F));
                    builder.AddCubicBezier(new Vector2(135.460999F, -153.139008F), new Vector2(-42.5F, 24.8220005F), new Vector2(-42.5F, 24.8220005F));
                    builder.AddCubicBezier(new Vector2(-42.5F, 24.8220005F), new Vector2(-109.887001F, -42.5649986F), new Vector2(-109.887001F, -42.5649986F));
                    builder.AddCubicBezier(new Vector2(-111.058998F, -43.7369995F), new Vector2(-112.958F, -43.7369995F), new Vector2(-114.129997F, -42.5649986F));
                    builder.AddCubicBezier(new Vector2(-114.129997F, -42.5649986F), new Vector2(-169.990997F, 13.2969999F), new Vector2(-169.990997F, 13.2969999F));
                    builder.AddCubicBezier(new Vector2(-171.162994F, 14.4689999F), new Vector2(-171.162994F, 16.368F), new Vector2(-169.990997F, 17.5400009F));
                    builder.AddCubicBezier(new Vector2(-169.990997F, 17.5400009F), new Vector2(-44.6209984F, 142.908997F), new Vector2(-44.6209984F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-43.4490013F, 144.080994F), new Vector2(-41.5509987F, 144.080994F), new Vector2(-40.3790016F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-40.3790016F, 142.908997F), new Vector2(195.565002F, -93.0350037F), new Vector2(195.565002F, -93.0350037F));
                    builder.AddCubicBezier(new Vector2(196.737F, -94.2070007F), new Vector2(196.737F, -96.1050034F), new Vector2(195.565002F, -97.2770004F));
                    builder.AddCubicBezier(new Vector2(195.565002F, -97.2770004F), new Vector2(139.703995F, -153.139008F), new Vector2(139.703995F, -153.139008F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_05()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-42.5079994F, 24.8220005F));
                    builder.AddCubicBezier(new Vector2(-42.5079994F, 24.8220005F), new Vector2(-42.4650002F, 24.7789993F), new Vector2(-42.4650002F, 24.7789993F));
                    builder.AddCubicBezier(new Vector2(-42.4650002F, 24.7789993F), new Vector2(-42.4650002F, 143.787994F), new Vector2(-42.4650002F, 143.787994F));
                    builder.AddCubicBezier(new Vector2(-43.2470016F, 143.798996F), new Vector2(-44.0320015F, 143.505997F), new Vector2(-44.6290016F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-44.6290016F, 142.908997F), new Vector2(-185.343994F, 2.19499993F), new Vector2(-185.343994F, 2.19499993F));
                    builder.AddCubicBezier(new Vector2(-186.516006F, 1.023F), new Vector2(-186.516006F, -0.875999987F), new Vector2(-185.343994F, -2.0480001F));
                    builder.AddCubicBezier(new Vector2(-185.343994F, -2.0480001F), new Vector2(-129.481995F, -57.9090004F), new Vector2(-129.481995F, -57.9090004F));
                    builder.AddCubicBezier(new Vector2(-128.311005F, -59.0800018F), new Vector2(-126.412003F, -59.0810013F), new Vector2(-125.239998F, -57.9099998F));
                    builder.AddCubicBezier(new Vector2(-125.239998F, -57.9099998F), new Vector2(-42.5079994F, 24.8220005F), new Vector2(-42.5079994F, 24.8220005F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - PreComp layer: hover-wobble
            // - - - - Layer aggregator
            // - - -  Offset:<217.457, 210.03>
            // - Path
            CanvasGeometry Geometry_06()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-42.5079994F, 24.8220005F));
                    builder.AddCubicBezier(new Vector2(-42.5079994F, 24.8220005F), new Vector2(-42.4650002F, 24.7789993F), new Vector2(-42.4650002F, 24.7789993F));
                    builder.AddCubicBezier(new Vector2(-42.4650002F, 24.7789993F), new Vector2(-42.4650002F, 143.787994F), new Vector2(-42.4650002F, 143.787994F));
                    builder.AddCubicBezier(new Vector2(-43.2470016F, 143.798996F), new Vector2(-44.0320015F, 143.505997F), new Vector2(-44.6290016F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-44.6290016F, 142.908997F), new Vector2(-205.343994F, -17.8050003F), new Vector2(-205.343994F, -17.8050003F));
                    builder.AddCubicBezier(new Vector2(-206.516006F, -18.9769993F), new Vector2(-206.516006F, -20.8759995F), new Vector2(-205.343994F, -22.0480003F));
                    builder.AddCubicBezier(new Vector2(-205.343994F, -22.0480003F), new Vector2(-149.481995F, -77.9089966F), new Vector2(-149.481995F, -77.9089966F));
                    builder.AddCubicBezier(new Vector2(-148.311005F, -79.0800018F), new Vector2(-146.412994F, -79.0810013F), new Vector2(-145.240997F, -77.9100037F));
                    builder.AddCubicBezier(new Vector2(-145.240997F, -77.9100037F), new Vector2(-42.5079994F, 24.8220005F), new Vector2(-42.5079994F, 24.8220005F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - PreComp layer: hover-wobble
            // - - - - Layer aggregator
            // - - -  Offset:<217.457, 210.03>
            // - Path
            CanvasGeometry Geometry_07()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-42.5079994F, 24.8220005F));
                    builder.AddCubicBezier(new Vector2(-42.5079994F, 24.8220005F), new Vector2(-42.4650002F, 24.7789993F), new Vector2(-42.4650002F, 24.7789993F));
                    builder.AddCubicBezier(new Vector2(-42.4650002F, 24.7789993F), new Vector2(-42.4650002F, 143.787994F), new Vector2(-42.4650002F, 143.787994F));
                    builder.AddCubicBezier(new Vector2(-43.2470016F, 143.798996F), new Vector2(-44.0320015F, 143.505997F), new Vector2(-44.6290016F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-44.6290016F, 142.908997F), new Vector2(-155.343994F, 32.1949997F), new Vector2(-155.343994F, 32.1949997F));
                    builder.AddCubicBezier(new Vector2(-156.516006F, 31.0230007F), new Vector2(-156.516006F, 29.1240005F), new Vector2(-155.343994F, 27.9519997F));
                    builder.AddCubicBezier(new Vector2(-155.343994F, 27.9519997F), new Vector2(-99.4820023F, -27.9090004F), new Vector2(-99.4820023F, -27.9090004F));
                    builder.AddCubicBezier(new Vector2(-98.310997F, -29.0799999F), new Vector2(-96.4120026F, -29.0809994F), new Vector2(-95.2399979F, -27.9099998F));
                    builder.AddCubicBezier(new Vector2(-95.2399979F, -27.9099998F), new Vector2(-42.5079994F, 24.8220005F), new Vector2(-42.5079994F, 24.8220005F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - PreComp layer: hover-wobble
            // - - - - Layer aggregator
            // - - -  Offset:<217.457, 210.03>
            // - Path
            CanvasGeometry Geometry_08()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-42.5079994F, 24.8220005F));
                    builder.AddCubicBezier(new Vector2(-42.5079994F, 24.8220005F), new Vector2(-42.4650002F, 24.7789993F), new Vector2(-42.4650002F, 24.7789993F));
                    builder.AddCubicBezier(new Vector2(-42.4650002F, 24.7789993F), new Vector2(-42.4650002F, 143.787994F), new Vector2(-42.4650002F, 143.787994F));
                    builder.AddCubicBezier(new Vector2(-43.2470016F, 143.798996F), new Vector2(-44.0320015F, 143.505997F), new Vector2(-44.6290016F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-44.6290016F, 142.908997F), new Vector2(-189.998993F, -2.46000004F), new Vector2(-189.998993F, -2.46000004F));
                    builder.AddCubicBezier(new Vector2(-191.171005F, -3.63199997F), new Vector2(-191.171005F, -5.53100014F), new Vector2(-189.998993F, -6.70300007F));
                    builder.AddCubicBezier(new Vector2(-189.998993F, -6.70300007F), new Vector2(-134.138F, -62.5649986F), new Vector2(-134.138F, -62.5649986F));
                    builder.AddCubicBezier(new Vector2(-132.966995F, -63.7360001F), new Vector2(-131.067993F, -63.7360001F), new Vector2(-129.895996F, -62.5649986F));
                    builder.AddCubicBezier(new Vector2(-129.895996F, -62.5649986F), new Vector2(-42.5079994F, 24.8220005F), new Vector2(-42.5079994F, 24.8220005F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - PreComp layer: hover-wobble
            // - - - - Layer aggregator
            // - - -  Offset:<217.457, 210.03>
            // - Path
            CanvasGeometry Geometry_09()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-42.5079994F, 24.8220005F));
                    builder.AddCubicBezier(new Vector2(-42.5079994F, 24.8220005F), new Vector2(-42.4650002F, 24.7789993F), new Vector2(-42.4650002F, 24.7789993F));
                    builder.AddCubicBezier(new Vector2(-42.4650002F, 24.7789993F), new Vector2(-42.4650002F, 143.787994F), new Vector2(-42.4650002F, 143.787994F));
                    builder.AddCubicBezier(new Vector2(-43.2470016F, 143.798996F), new Vector2(-44.0320015F, 143.505997F), new Vector2(-44.6290016F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-44.6290016F, 142.908997F), new Vector2(-169.998993F, 17.5400009F), new Vector2(-169.998993F, 17.5400009F));
                    builder.AddCubicBezier(new Vector2(-171.171005F, 16.368F), new Vector2(-171.171005F, 14.4689999F), new Vector2(-169.998993F, 13.2969999F));
                    builder.AddCubicBezier(new Vector2(-169.998993F, 13.2969999F), new Vector2(-114.138F, -42.5649986F), new Vector2(-114.138F, -42.5649986F));
                    builder.AddCubicBezier(new Vector2(-112.967003F, -43.7360001F), new Vector2(-111.068001F, -43.7360001F), new Vector2(-109.896004F, -42.5649986F));
                    builder.AddCubicBezier(new Vector2(-109.896004F, -42.5649986F), new Vector2(-42.5079994F, 24.8220005F), new Vector2(-42.5079994F, 24.8220005F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_10()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(129.473999F, -142.908997F));
                    builder.AddCubicBezier(new Vector2(128.302002F, -144.080994F), new Vector2(126.403999F, -144.080994F), new Vector2(125.232002F, -142.908997F));
                    builder.AddCubicBezier(new Vector2(125.232002F, -142.908997F), new Vector2(-42.5F, 24.8220005F), new Vector2(-42.5F, 24.8220005F));
                    builder.AddCubicBezier(new Vector2(-42.5F, 24.8220005F), new Vector2(-125.231003F, -57.9090004F), new Vector2(-125.231003F, -57.9090004F));
                    builder.AddCubicBezier(new Vector2(-126.403F, -59.0810013F), new Vector2(-128.302002F, -59.0810013F), new Vector2(-129.473999F, -57.9090004F));
                    builder.AddCubicBezier(new Vector2(-129.473999F, -57.9090004F), new Vector2(-185.335999F, -2.0480001F), new Vector2(-185.335999F, -2.0480001F));
                    builder.AddCubicBezier(new Vector2(-186.507996F, -0.875999987F), new Vector2(-186.507996F, 1.023F), new Vector2(-185.335999F, 2.19499993F));
                    builder.AddCubicBezier(new Vector2(-185.335999F, 2.19499993F), new Vector2(-44.6209984F, 142.908997F), new Vector2(-44.6209984F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-43.4490013F, 144.080994F), new Vector2(-41.5509987F, 144.080994F), new Vector2(-40.3790016F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-40.3790016F, 142.908997F), new Vector2(185.335999F, -82.8050003F), new Vector2(185.335999F, -82.8050003F));
                    builder.AddCubicBezier(new Vector2(186.507996F, -83.9769974F), new Vector2(186.507996F, -85.8759995F), new Vector2(185.335999F, -87.0479965F));
                    builder.AddCubicBezier(new Vector2(185.335999F, -87.0479965F), new Vector2(129.473999F, -142.908997F), new Vector2(129.473999F, -142.908997F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - PreComp layer: hover-wobble
            // - - - - Layer aggregator
            // - - -  Offset:<217.457, 210.03>
            // - Path
            CanvasGeometry Geometry_11()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(89.473999F, -102.908997F));
                    builder.AddCubicBezier(new Vector2(88.302002F, -104.081001F), new Vector2(86.4039993F, -104.081001F), new Vector2(85.2320023F, -102.908997F));
                    builder.AddCubicBezier(new Vector2(85.2320023F, -102.908997F), new Vector2(-42.5F, 24.8220005F), new Vector2(-42.5F, 24.8220005F));
                    builder.AddCubicBezier(new Vector2(-42.5F, 24.8220005F), new Vector2(-145.231995F, -77.9089966F), new Vector2(-145.231995F, -77.9089966F));
                    builder.AddCubicBezier(new Vector2(-146.404007F, -79.0810013F), new Vector2(-148.302002F, -79.0810013F), new Vector2(-149.473999F, -77.9089966F));
                    builder.AddCubicBezier(new Vector2(-149.473999F, -77.9089966F), new Vector2(-205.335999F, -22.0480003F), new Vector2(-205.335999F, -22.0480003F));
                    builder.AddCubicBezier(new Vector2(-206.507996F, -20.8759995F), new Vector2(-206.507996F, -18.9769993F), new Vector2(-205.335999F, -17.8050003F));
                    builder.AddCubicBezier(new Vector2(-205.335999F, -17.8050003F), new Vector2(-44.6209984F, 142.908997F), new Vector2(-44.6209984F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-43.4490013F, 144.080994F), new Vector2(-41.5509987F, 144.080994F), new Vector2(-40.3790016F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-40.3790016F, 142.908997F), new Vector2(145.335999F, -42.8050003F), new Vector2(145.335999F, -42.8050003F));
                    builder.AddCubicBezier(new Vector2(146.507996F, -43.9770012F), new Vector2(146.507996F, -45.8759995F), new Vector2(145.335999F, -47.0480003F));
                    builder.AddCubicBezier(new Vector2(145.335999F, -47.0480003F), new Vector2(89.473999F, -102.908997F), new Vector2(89.473999F, -102.908997F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - PreComp layer: hover-wobble
            // - - - - Layer aggregator
            // - - -  Offset:<217.457, 210.03>
            // - Path
            CanvasGeometry Geometry_12()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(149.473999F, -162.908997F));
                    builder.AddCubicBezier(new Vector2(148.302002F, -164.080994F), new Vector2(146.404007F, -164.080994F), new Vector2(145.231995F, -162.908997F));
                    builder.AddCubicBezier(new Vector2(145.231995F, -162.908997F), new Vector2(-42.5F, 24.8220005F), new Vector2(-42.5F, 24.8220005F));
                    builder.AddCubicBezier(new Vector2(-42.5F, 24.8220005F), new Vector2(-95.2310028F, -27.9090004F), new Vector2(-95.2310028F, -27.9090004F));
                    builder.AddCubicBezier(new Vector2(-96.4029999F, -29.0809994F), new Vector2(-98.302002F, -29.0809994F), new Vector2(-99.473999F, -27.9090004F));
                    builder.AddCubicBezier(new Vector2(-99.473999F, -27.9090004F), new Vector2(-155.335999F, 27.9519997F), new Vector2(-155.335999F, 27.9519997F));
                    builder.AddCubicBezier(new Vector2(-156.507996F, 29.1240005F), new Vector2(-156.507996F, 31.0230007F), new Vector2(-155.335999F, 32.1949997F));
                    builder.AddCubicBezier(new Vector2(-155.335999F, 32.1949997F), new Vector2(-44.6209984F, 142.908997F), new Vector2(-44.6209984F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-43.4490013F, 144.080994F), new Vector2(-41.5509987F, 144.080994F), new Vector2(-40.3790016F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-40.3790016F, 142.908997F), new Vector2(205.335999F, -102.805F), new Vector2(205.335999F, -102.805F));
                    builder.AddCubicBezier(new Vector2(206.507996F, -103.976997F), new Vector2(206.507996F, -105.875999F), new Vector2(205.335999F, -107.047997F));
                    builder.AddCubicBezier(new Vector2(205.335999F, -107.047997F), new Vector2(149.473999F, -162.908997F), new Vector2(149.473999F, -162.908997F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - PreComp layer: hover-wobble
            // - - - - Layer aggregator
            // - - -  Offset:<217.457, 210.03>
            // - Path
            CanvasGeometry Geometry_13()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(119.704002F, -133.139008F));
                    builder.AddCubicBezier(new Vector2(118.531998F, -134.311005F), new Vector2(116.633003F, -134.311005F), new Vector2(115.460999F, -133.139008F));
                    builder.AddCubicBezier(new Vector2(115.460999F, -133.139008F), new Vector2(-42.5F, 24.8220005F), new Vector2(-42.5F, 24.8220005F));
                    builder.AddCubicBezier(new Vector2(-42.5F, 24.8220005F), new Vector2(-129.886993F, -62.5649986F), new Vector2(-129.886993F, -62.5649986F));
                    builder.AddCubicBezier(new Vector2(-131.059006F, -63.7369995F), new Vector2(-132.957993F, -63.7369995F), new Vector2(-134.130005F, -62.5649986F));
                    builder.AddCubicBezier(new Vector2(-134.130005F, -62.5649986F), new Vector2(-189.990997F, -6.70300007F), new Vector2(-189.990997F, -6.70300007F));
                    builder.AddCubicBezier(new Vector2(-191.162994F, -5.53100014F), new Vector2(-191.162994F, -3.6329999F), new Vector2(-189.990997F, -2.46099997F));
                    builder.AddCubicBezier(new Vector2(-189.990997F, -2.46099997F), new Vector2(-44.6209984F, 142.908997F), new Vector2(-44.6209984F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-43.4490013F, 144.080994F), new Vector2(-41.5509987F, 144.080994F), new Vector2(-40.3790016F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-40.3790016F, 142.908997F), new Vector2(175.565002F, -73.0350037F), new Vector2(175.565002F, -73.0350037F));
                    builder.AddCubicBezier(new Vector2(176.737F, -74.2070007F), new Vector2(176.737F, -76.1050034F), new Vector2(175.565002F, -77.2770004F));
                    builder.AddCubicBezier(new Vector2(175.565002F, -77.2770004F), new Vector2(119.704002F, -133.139008F), new Vector2(119.704002F, -133.139008F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - - PreComp layer: hover-wobble
            // - - - - Layer aggregator
            // - - -  Offset:<217.457, 210.03>
            // - Path
            CanvasGeometry Geometry_14()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(139.703995F, -153.139008F));
                    builder.AddCubicBezier(new Vector2(138.531998F, -154.311005F), new Vector2(136.632996F, -154.311005F), new Vector2(135.460999F, -153.139008F));
                    builder.AddCubicBezier(new Vector2(135.460999F, -153.139008F), new Vector2(-42.5F, 24.8220005F), new Vector2(-42.5F, 24.8220005F));
                    builder.AddCubicBezier(new Vector2(-42.5F, 24.8220005F), new Vector2(-109.887001F, -42.5649986F), new Vector2(-109.887001F, -42.5649986F));
                    builder.AddCubicBezier(new Vector2(-111.058998F, -43.7369995F), new Vector2(-112.958F, -43.7369995F), new Vector2(-114.129997F, -42.5649986F));
                    builder.AddCubicBezier(new Vector2(-114.129997F, -42.5649986F), new Vector2(-169.990997F, 13.2969999F), new Vector2(-169.990997F, 13.2969999F));
                    builder.AddCubicBezier(new Vector2(-171.162994F, 14.4689999F), new Vector2(-171.162994F, 16.368F), new Vector2(-169.990997F, 17.5400009F));
                    builder.AddCubicBezier(new Vector2(-169.990997F, 17.5400009F), new Vector2(-44.6209984F, 142.908997F), new Vector2(-44.6209984F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-43.4490013F, 144.080994F), new Vector2(-41.5509987F, 144.080994F), new Vector2(-40.3790016F, 142.908997F));
                    builder.AddCubicBezier(new Vector2(-40.3790016F, 142.908997F), new Vector2(195.565002F, -93.0350037F), new Vector2(195.565002F, -93.0350037F));
                    builder.AddCubicBezier(new Vector2(196.737F, -94.2070007F), new Vector2(196.737F, -96.1050034F), new Vector2(195.565002F, -97.2770004F));
                    builder.AddCubicBezier(new Vector2(195.565002F, -97.2770004F), new Vector2(139.703995F, -153.139008F), new Vector2(139.703995F, -153.139008F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - PreComp layer: hover-wobble
            // - Layer aggregator
            // Offset:<217.457, 210.03>
            CompositionColorBrush ColorBrush_AlmostBlack_FF121330()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0x12, 0x13, 0x30));
            }

            // - - PreComp layer: hover-wobble
            // - Layer aggregator
            // Offset:<217.457, 210.03>
            CompositionColorBrush ColorBrush_AlmostLightSeaGreen_FF2CA48D()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0x2C, 0xA4, 0x8D));
            }

            // - - PreComp layer: hover-wobble
            // - Layer aggregator
            // Offset:<217.457, 210.03>
            CompositionColorBrush ColorBrush_SemiTransparentAlmostLightSeaGreen_7F2CA48D()
            {
                return _c.CreateColorBrush(Color.FromArgb(0x7F, 0x2C, 0xA4, 0x8D));
            }

            CompositionPath Path_0()
            {
                if (_path_0 != null) { return _path_0; }
                var result = _path_0 = new CompositionPath(Geometry_00());
                return result;
            }

            CompositionPath Path_1()
            {
                if (_path_1 != null) { return _path_1; }
                var result = _path_1 = new CompositionPath(Geometry_05());
                return result;
            }

            CompositionPath Path_2()
            {
                if (_path_2 != null) { return _path_2; }
                var result = _path_2 = new CompositionPath(Geometry_10());
                return result;
            }

            // - - PreComp layer: hover-wobble
            // - Layer aggregator
            // Offset:<217.457, 210.03>
            CompositionPathGeometry PathGeometry_0()
            {
                if (_pathGeometry_0 != null) { return _pathGeometry_0; }
                var result = _pathGeometry_0 = _c.CreatePathGeometry();
                return result;
            }

            // - - PreComp layer: hover-wobble
            // - Layer aggregator
            // Offset:<217.457, 210.03>
            CompositionPathGeometry PathGeometry_1()
            {
                if (_pathGeometry_1 != null) { return _pathGeometry_1; }
                var result = _pathGeometry_1 = _c.CreatePathGeometry();
                return result;
            }

            // - - PreComp layer: hover-wobble
            // - Layer aggregator
            // Offset:<217.457, 210.03>
            CompositionPathGeometry PathGeometry_2()
            {
                if (_pathGeometry_2 != null) { return _pathGeometry_2; }
                var result = _pathGeometry_2 = _c.CreatePathGeometry();
                return result;
            }

            // - PreComp layer: hover-wobble
            // Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_0()
            {
                // Offset:<217.457, 210.03>
                var geometry = PathGeometry_0();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 217.457001F, 210.029999F), ColorBrush_AlmostLightSeaGreen_FF2CA48D());;
                return result;
            }

            // - PreComp layer: hover-wobble
            // Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_1()
            {
                // Offset:<217.457, 210.03>
                var geometry = PathGeometry_1();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 217.457001F, 210.029999F), ColorBrush_SemiTransparentAlmostLightSeaGreen_7F2CA48D());;
                return result;
            }

            // - PreComp layer: hover-wobble
            // Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_2()
            {
                // Offset:<217.457, 210.03>
                var result = CreateSpriteShape(PathGeometry_2(), new Matrix3x2(1F, 0F, 0F, 1F, 217.457001F, 210.029999F));;
                result.StrokeBrush = ColorBrush_AlmostBlack_FF121330();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 7F;
                return result;
            }

            // Transforms for hover-wobble Scale(1,1,0)
            ContainerVisual ContainerVisual_0()
            {
                var result = _c.CreateContainerVisual();
                result.Clip = InsetClip_0();
                result.Size = new Vector2(430F, 430F);
                // Scale:<1, 1>
                result.TransformMatrix = new Matrix4x4(1F, 0F, 0F, 0F, 0F, 1F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 1F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // PreComp layer: hover-wobble
                result.Children.InsertAtTop(ContainerVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.300999999F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return (_cubicBezierEasingFunction_1 == null)
                    ? _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.867999971F, 0F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_1;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_2()
            {
                return (_cubicBezierEasingFunction_2 == null)
                    ? _cubicBezierEasingFunction_2 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_2;
            }

            // PreComp layer: hover-wobble
            InsetClip InsetClip_0()
            {
                var result = _c.CreateInsetClip();
                return result;
            }

            // - - - PreComp layer: hover-wobble
            // - - Layer aggregator
            // -  Offset:<217.457, 210.03>
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_0()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_0(), HoldThenStepEasingFunction());
                // Frame 17.
                result.InsertKeyFrame(0.283333331F, new CompositionPath(Geometry_01()), CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(0.5F, new CompositionPath(Geometry_02()), CubicBezierEasingFunction_1());
                // Frame 43.
                result.InsertKeyFrame(0.716666639F, new CompositionPath(Geometry_03()), CubicBezierEasingFunction_2());
                // Frame 51.
                result.InsertKeyFrame(0.850000024F, new CompositionPath(Geometry_04()), CubicBezierEasingFunction_2());
                // Frame 60.
                result.InsertKeyFrame(1F, Path_0(), CubicBezierEasingFunction_2());
                return result;
            }

            // - - - PreComp layer: hover-wobble
            // - - Layer aggregator
            // -  Offset:<217.457, 210.03>
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_1()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_1(), HoldThenStepEasingFunction());
                // Frame 17.
                result.InsertKeyFrame(0.283333331F, new CompositionPath(Geometry_06()), CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(0.5F, new CompositionPath(Geometry_07()), CubicBezierEasingFunction_1());
                // Frame 43.
                result.InsertKeyFrame(0.716666639F, new CompositionPath(Geometry_08()), CubicBezierEasingFunction_2());
                // Frame 51.
                result.InsertKeyFrame(0.850000024F, new CompositionPath(Geometry_09()), CubicBezierEasingFunction_2());
                // Frame 60.
                result.InsertKeyFrame(1F, Path_1(), CubicBezierEasingFunction_2());
                return result;
            }

            // - - - PreComp layer: hover-wobble
            // - - Layer aggregator
            // -  Offset:<217.457, 210.03>
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_2()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_2(), HoldThenStepEasingFunction());
                // Frame 17.
                result.InsertKeyFrame(0.283333331F, new CompositionPath(Geometry_11()), CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(0.5F, new CompositionPath(Geometry_12()), CubicBezierEasingFunction_1());
                // Frame 43.
                result.InsertKeyFrame(0.716666639F, new CompositionPath(Geometry_13()), CubicBezierEasingFunction_2());
                // Frame 51.
                result.InsertKeyFrame(0.850000024F, new CompositionPath(Geometry_14()), CubicBezierEasingFunction_2());
                // Frame 60.
                result.InsertKeyFrame(1F, Path_2(), CubicBezierEasingFunction_2());
                return result;
            }

            // PreComp layer: hover-wobble
            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(430F, 430F);
                var shapes = result.Shapes;
                // Offset:<217.457, 210.03>
                shapes.Add(SpriteShape_0());
                // Offset:<217.457, 210.03>
                shapes.Add(SpriteShape_1());
                // Offset:<217.457, 210.03>
                shapes.Add(SpriteShape_2());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            internal Wired_lineal_37_check_hover_wobble_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(430F, 430F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _pathGeometry_0.StartAnimation("Path", PathKeyFrameAnimation_0(), AnimationController_0());
                _pathGeometry_1.StartAnimation("Path", PathKeyFrameAnimation_1(), AnimationController_0());
                _pathGeometry_2.StartAnimation("Path", PathKeyFrameAnimation_2(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _pathGeometry_0.StopAnimation("Path");
                _pathGeometry_1.StopAnimation("Path");
                _pathGeometry_2.StopAnimation("Path");
            }

        }
    }
}
